provider: sdwan
major-version: 0
makeTemplate: bridged
plugins:
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.16"
    kind: converter
team: ecosystem
providerDefaultBranch: main
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
esc:
  enabled: true
  environment: imports/github-secrets # No repo-specific secrets.
