provider: sdwan
major-version: 0
makeTemplate: bridged
team: ecosystem
providerDefaultBranch: main
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
