// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan
{
    /// <summary>
    /// This resource can manage a Service LAN VPN Interface SVI Feature Associate DHCP Server Feature .
    ///   - Minimum SD-WAN Manager version: `20.12.0`
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Sdwan = Pulumi.Sdwan;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Sdwan.ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature("example", new()
    ///     {
    ///         FeatureProfileId = "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac",
    ///         ServiceLanVpnFeatureId = "140331f6-5418-4755-a059-13c77eb96037",
    ///         ServiceLanVpnInterfaceSviFeatureId = "140331f6-5418-4755-a059-13c77eb96037",
    ///         ServiceDhcpServerFeatureId = "140331f6-5418-4755-a059-13c77eb96037",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Expected import identifier with the format: "service_lan_vpn_interface_svi_feature_associate_dhcp_server_feature_id,feature_profile_id,service_lan_vpn_feature_id,service_lan_vpn_interface_svi_feature_id"
    /// 
    /// ```sh
    /// $ pulumi import sdwan:index/serviceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature:ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature example "f6b2c44c-693c-4763-b010-895aa3d236bd,f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac,140331f6-5418-4755-a059-13c77eb96037,140331f6-5418-4755-a059-13c77eb96037"
    /// ```
    /// </summary>
    [SdwanResourceType("sdwan:index/serviceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature:ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature")]
    public partial class ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Feature Profile ID
        /// </summary>
        [Output("featureProfileId")]
        public Output<string> FeatureProfileId { get; private set; } = null!;

        /// <summary>
        /// Service DHCP Server Feature ID
        /// </summary>
        [Output("serviceDhcpServerFeatureId")]
        public Output<string> ServiceDhcpServerFeatureId { get; private set; } = null!;

        /// <summary>
        /// Service LAN VPN Feature ID
        /// </summary>
        [Output("serviceLanVpnFeatureId")]
        public Output<string> ServiceLanVpnFeatureId { get; private set; } = null!;

        /// <summary>
        /// Service LAN VPN Interface SVI Feature ID
        /// </summary>
        [Output("serviceLanVpnInterfaceSviFeatureId")]
        public Output<string> ServiceLanVpnInterfaceSviFeatureId { get; private set; } = null!;

        /// <summary>
        /// The version of the object
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature(string name, ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureArgs args, CustomResourceOptions? options = null)
            : base("sdwan:index/serviceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature:ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature", name, args ?? new ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature(string name, Input<string> id, ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureState? state = null, CustomResourceOptions? options = null)
            : base("sdwan:index/serviceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature:ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature Get(string name, Input<string> id, ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureState? state = null, CustomResourceOptions? options = null)
        {
            return new ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeature(name, id, state, options);
        }
    }

    public sealed class ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Feature Profile ID
        /// </summary>
        [Input("featureProfileId", required: true)]
        public Input<string> FeatureProfileId { get; set; } = null!;

        /// <summary>
        /// Service DHCP Server Feature ID
        /// </summary>
        [Input("serviceDhcpServerFeatureId", required: true)]
        public Input<string> ServiceDhcpServerFeatureId { get; set; } = null!;

        /// <summary>
        /// Service LAN VPN Feature ID
        /// </summary>
        [Input("serviceLanVpnFeatureId", required: true)]
        public Input<string> ServiceLanVpnFeatureId { get; set; } = null!;

        /// <summary>
        /// Service LAN VPN Interface SVI Feature ID
        /// </summary>
        [Input("serviceLanVpnInterfaceSviFeatureId", required: true)]
        public Input<string> ServiceLanVpnInterfaceSviFeatureId { get; set; } = null!;

        public ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureArgs()
        {
        }
        public static new ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureArgs Empty => new ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureArgs();
    }

    public sealed class ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Feature Profile ID
        /// </summary>
        [Input("featureProfileId")]
        public Input<string>? FeatureProfileId { get; set; }

        /// <summary>
        /// Service DHCP Server Feature ID
        /// </summary>
        [Input("serviceDhcpServerFeatureId")]
        public Input<string>? ServiceDhcpServerFeatureId { get; set; }

        /// <summary>
        /// Service LAN VPN Feature ID
        /// </summary>
        [Input("serviceLanVpnFeatureId")]
        public Input<string>? ServiceLanVpnFeatureId { get; set; }

        /// <summary>
        /// Service LAN VPN Interface SVI Feature ID
        /// </summary>
        [Input("serviceLanVpnInterfaceSviFeatureId")]
        public Input<string>? ServiceLanVpnInterfaceSviFeatureId { get; set; }

        /// <summary>
        /// The version of the object
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureState()
        {
        }
        public static new ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureState Empty => new ServiceLanVpnInterfaceSviFeatureAssociateDhcpServerFeatureState();
    }
}
