// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class CiscoTrustsecFeatureTemplateSxpConnection
    {
        /// <summary>
        /// Configure Connection Maximum hold time &lt;0..65535&gt;
        ///   - Range: `0`-`65535`
        ///   - Default value: `0`
        /// </summary>
        public readonly int? MaximumHoldTime;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? MaximumHoldTimeVariable;
        /// <summary>
        /// Configure Connection Minimum hold time &lt;0..65535&gt;
        ///   - Range: `0`-`65535`
        ///   - Default value: `0`
        /// </summary>
        public readonly int? MinimumHoldTime;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? MinimumHoldTimeVariable;
        /// <summary>
        /// Define Mode of connection
        ///   - Choices: `local`, `peer`
        ///   - Default value: `local`
        /// </summary>
        public readonly string? Mode;
        /// <summary>
        /// Define Role of a device &lt;speaker/listener/both&gt;
        ///   - Choices: `listener`, `speaker`, `both`
        ///   - Default value: `speaker`
        /// </summary>
        public readonly string? ModeType;
        /// <summary>
        /// Indicates if list item is considered optional.
        /// </summary>
        public readonly bool? Optional;
        /// <summary>
        /// Configure SXP Peer IP address (IPv4)
        /// </summary>
        public readonly string? PeerIp;
        /// <summary>
        /// Define Preshared Key type
        ///   - Choices: `default`, `key-chain`, `none`
        ///   - Default value: `none`
        /// </summary>
        public readonly string? PresharedKey;
        /// <summary>
        /// Configure SXP Source IP address (IPv4)
        /// </summary>
        public readonly string? SourceIp;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? SourceIpVariable;
        /// <summary>
        /// Configure Connection VPN (VRF) ID
        ///   - Range: `0`-`65527`
        ///   - Default value: `0`
        /// </summary>
        public readonly int? VpnId;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? VpnIdVariable;

        [OutputConstructor]
        private CiscoTrustsecFeatureTemplateSxpConnection(
            int? maximumHoldTime,

            string? maximumHoldTimeVariable,

            int? minimumHoldTime,

            string? minimumHoldTimeVariable,

            string? mode,

            string? modeType,

            bool? optional,

            string? peerIp,

            string? presharedKey,

            string? sourceIp,

            string? sourceIpVariable,

            int? vpnId,

            string? vpnIdVariable)
        {
            MaximumHoldTime = maximumHoldTime;
            MaximumHoldTimeVariable = maximumHoldTimeVariable;
            MinimumHoldTime = minimumHoldTime;
            MinimumHoldTimeVariable = minimumHoldTimeVariable;
            Mode = mode;
            ModeType = modeType;
            Optional = optional;
            PeerIp = peerIp;
            PresharedKey = presharedKey;
            SourceIp = sourceIp;
            SourceIpVariable = sourceIpVariable;
            VpnId = vpnId;
            VpnIdVariable = vpnIdVariable;
        }
    }
}
