// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class CiscoOspfv3FeatureTemplateIpv6AreaRange
    {
        /// <summary>
        /// Set Matching Prefix
        /// </summary>
        public readonly string? Address;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? AddressVariable;
        /// <summary>
        /// Set cost for this range
        ///   - Range: `0`-`16777214`
        /// </summary>
        public readonly int? Cost;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? CostVariable;
        /// <summary>
        /// Do not advertise this range
        ///   - Default value: `false`
        /// </summary>
        public readonly bool? NoAdvertise;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? NoAdvertiseVariable;
        /// <summary>
        /// Indicates if list item is considered optional.
        /// </summary>
        public readonly bool? Optional;

        [OutputConstructor]
        private CiscoOspfv3FeatureTemplateIpv6AreaRange(
            string? address,

            string? addressVariable,

            int? cost,

            string? costVariable,

            bool? noAdvertise,

            string? noAdvertiseVariable,

            bool? optional)
        {
            Address = address;
            AddressVariable = addressVariable;
            Cost = cost;
            CostVariable = costVariable;
            NoAdvertise = noAdvertise;
            NoAdvertiseVariable = noAdvertiseVariable;
            Optional = optional;
        }
    }
}
