// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class CiscoVpnFeatureTemplateStaticNatSubnetRule
    {
        /// <summary>
        /// Indicates if list item is considered optional.
        /// </summary>
        public readonly bool? Optional;
        /// <summary>
        /// Network Prefix Length
        ///   - Range: `1`-`32`
        /// </summary>
        public readonly int? PrefixLength;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? PrefixLengthVariable;
        /// <summary>
        /// Source IP Subnet to be translated
        /// </summary>
        public readonly string? SourceIpSubnet;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? SourceIpSubnetVariable;
        /// <summary>
        /// Direction of static NAT translation
        ///   - Choices: `Inside`, `Outside`
        /// </summary>
        public readonly string? StaticNatDirection;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? StaticNatDirectionVariable;
        /// <summary>
        /// Add Object/Object Group Tracker
        ///   - Range: `1`-`1000`
        /// </summary>
        public readonly int? TrackerId;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? TrackerIdVariable;
        /// <summary>
        /// Statically translated source IP Subnet
        /// </summary>
        public readonly string? TranslateIpSubnet;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? TranslateIpSubnetVariable;

        [OutputConstructor]
        private CiscoVpnFeatureTemplateStaticNatSubnetRule(
            bool? optional,

            int? prefixLength,

            string? prefixLengthVariable,

            string? sourceIpSubnet,

            string? sourceIpSubnetVariable,

            string? staticNatDirection,

            string? staticNatDirectionVariable,

            int? trackerId,

            string? trackerIdVariable,

            string? translateIpSubnet,

            string? translateIpSubnetVariable)
        {
            Optional = optional;
            PrefixLength = prefixLength;
            PrefixLengthVariable = prefixLengthVariable;
            SourceIpSubnet = sourceIpSubnet;
            SourceIpSubnetVariable = sourceIpSubnetVariable;
            StaticNatDirection = staticNatDirection;
            StaticNatDirectionVariable = staticNatDirectionVariable;
            TrackerId = trackerId;
            TrackerIdVariable = trackerIdVariable;
            TranslateIpSubnet = translateIpSubnet;
            TranslateIpSubnetVariable = translateIpSubnetVariable;
        }
    }
}
