// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class ConfigurationGroupDeviceVariablesGroup
    {
        /// <summary>
        /// Group name
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// List of variables
        /// </summary>
        public readonly ImmutableArray<Outputs.ConfigurationGroupDeviceVariablesGroupVariable> Variables;

        [OutputConstructor]
        private ConfigurationGroupDeviceVariablesGroup(
            string? name,

            ImmutableArray<Outputs.ConfigurationGroupDeviceVariablesGroupVariable> variables)
        {
            Name = name;
            Variables = variables;
        }
    }
}
