// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class EmbeddedSecurityNgfwPolicySequence
    {
        /// <summary>
        /// can be empty array or with type or parameter
        /// </summary>
        public readonly ImmutableArray<Outputs.EmbeddedSecurityNgfwPolicySequenceAction> Actions;
        /// <summary>
        /// - Choices: `Pass`, `Inspect`, `Drop`
        /// </summary>
        public readonly string? BaseAction;
        public readonly bool? DisableSequence;
        public readonly ImmutableArray<Outputs.EmbeddedSecurityNgfwPolicySequenceMatchEntry> MatchEntries;
        public readonly string? SequenceId;
        public readonly string? SequenceName;
        public readonly string? SequenceType;

        [OutputConstructor]
        private EmbeddedSecurityNgfwPolicySequence(
            ImmutableArray<Outputs.EmbeddedSecurityNgfwPolicySequenceAction> actions,

            string? baseAction,

            bool? disableSequence,

            ImmutableArray<Outputs.EmbeddedSecurityNgfwPolicySequenceMatchEntry> matchEntries,

            string? sequenceId,

            string? sequenceName,

            string? sequenceType)
        {
            Actions = actions;
            BaseAction = baseAction;
            DisableSequence = disableSequence;
            MatchEntries = matchEntries;
            SequenceId = sequenceId;
            SequenceName = sequenceName;
            SequenceType = sequenceType;
        }
    }
}
