// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class GetSystemSecurityProfileParcelKeychainResult
    {
        /// <summary>
        /// Specify the name of the Keychain
        /// </summary>
        public readonly string KeyChainName;
        /// <summary>
        /// Specify the Key ID
        /// </summary>
        public readonly int KeyId;

        [OutputConstructor]
        private GetSystemSecurityProfileParcelKeychainResult(
            string keyChainName,

            int keyId)
        {
            KeyChainName = keyChainName;
            KeyId = keyId;
        }
    }
}
