// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class GetServiceLanVpnFeatureIpv4ExportRouteTargetResult
    {
        /// <summary>
        /// Route target
        /// </summary>
        public readonly string RouteTarget;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string RouteTargetVariable;

        [OutputConstructor]
        private GetServiceLanVpnFeatureIpv4ExportRouteTargetResult(
            string routeTarget,

            string routeTargetVariable)
        {
            RouteTarget = routeTarget;
            RouteTargetVariable = routeTargetVariable;
        }
    }
}
