// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class RoutePolicyDefinitionSequence
    {
        /// <summary>
        /// List of action entries
        /// </summary>
        public readonly ImmutableArray<Outputs.RoutePolicyDefinitionSequenceActionEntry> ActionEntries;
        /// <summary>
        /// Base action, either `Accept` or `Reject`
        ///   - Choices: `Accept`, `Reject`
        /// </summary>
        public readonly string? BaseAction;
        /// <summary>
        /// Sequence ID
        ///   - Range: `1`-`65534`
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// IP version, either `Ipv4` or `Ipv6`
        ///   - Choices: `Ipv4`, `Ipv6`
        /// </summary>
        public readonly string? IpType;
        /// <summary>
        /// List of match entries
        /// </summary>
        public readonly ImmutableArray<Outputs.RoutePolicyDefinitionSequenceMatchEntry> MatchEntries;
        /// <summary>
        /// Sequence name
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private RoutePolicyDefinitionSequence(
            ImmutableArray<Outputs.RoutePolicyDefinitionSequenceActionEntry> actionEntries,

            string? baseAction,

            int id,

            string? ipType,

            ImmutableArray<Outputs.RoutePolicyDefinitionSequenceMatchEntry> matchEntries,

            string name)
        {
            ActionEntries = actionEntries;
            BaseAction = baseAction;
            Id = id;
            IpType = ipType;
            MatchEntries = matchEntries;
            Name = name;
        }
    }
}
