// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class ServiceRoutingOspfv3Ipv6FeatureAreaRange
    {
        /// <summary>
        /// Set cost for this range
        ///   - Range: `0`-`16777214`
        /// </summary>
        public readonly int? Cost;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? CostVariable;
        /// <summary>
        /// Do not advertise this range
        ///   - Default value: `false`
        /// </summary>
        public readonly bool? NoAdvertise;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? NoAdvertiseVariable;
        /// <summary>
        /// IPv6 prefix,for example 2001::/64
        /// </summary>
        public readonly string? Prefix;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? PrefixVariable;

        [OutputConstructor]
        private ServiceRoutingOspfv3Ipv6FeatureAreaRange(
            int? cost,

            string? costVariable,

            bool? noAdvertise,

            string? noAdvertiseVariable,

            string? prefix,

            string? prefixVariable)
        {
            Cost = cost;
            CostVariable = costVariable;
            NoAdvertise = noAdvertise;
            NoAdvertiseVariable = noAdvertiseVariable;
            Prefix = prefix;
            PrefixVariable = prefixVariable;
        }
    }
}
