// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Outputs
{

    [OutputType]
    public sealed class ServiceLanVpnInterfaceSviFeatureIpv6Vrrp
    {
        /// <summary>
        /// IPv6 VRRP
        /// </summary>
        public readonly ImmutableArray<Outputs.ServiceLanVpnInterfaceSviFeatureIpv6VrrpAddress> Addresses;
        /// <summary>
        /// Group ID
        ///   - Range: `1`-`255`
        /// </summary>
        public readonly int? GroupId;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? GroupIdVariable;
        /// <summary>
        /// Set priority
        ///   - Range: `1`-`254`
        ///   - Default value: `100`
        /// </summary>
        public readonly int? Priority;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? PriorityVariable;
        /// <summary>
        /// IPv6 Secondary IP address
        /// </summary>
        public readonly ImmutableArray<Outputs.ServiceLanVpnInterfaceSviFeatureIpv6VrrpSecondaryAddress> SecondaryAddresses;
        /// <summary>
        /// Timer interval for successive advertisements, in milliseconds
        ///   - Range: `100`-`40950`
        ///   - Default value: `1000`
        /// </summary>
        public readonly int? Timer;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? TimerVariable;
        /// <summary>
        /// Track OMP status
        ///   - Default value: `false`
        /// </summary>
        public readonly bool? TrackOmp;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? TrackOmpVariable;
        /// <summary>
        /// Track Prefix List
        /// </summary>
        public readonly string? TrackPrefixList;
        /// <summary>
        /// Variable name
        /// </summary>
        public readonly string? TrackPrefixListVariable;

        [OutputConstructor]
        private ServiceLanVpnInterfaceSviFeatureIpv6Vrrp(
            ImmutableArray<Outputs.ServiceLanVpnInterfaceSviFeatureIpv6VrrpAddress> addresses,

            int? groupId,

            string? groupIdVariable,

            int? priority,

            string? priorityVariable,

            ImmutableArray<Outputs.ServiceLanVpnInterfaceSviFeatureIpv6VrrpSecondaryAddress> secondaryAddresses,

            int? timer,

            string? timerVariable,

            bool? trackOmp,

            string? trackOmpVariable,

            string? trackPrefixList,

            string? trackPrefixListVariable)
        {
            Addresses = addresses;
            GroupId = groupId;
            GroupIdVariable = groupIdVariable;
            Priority = priority;
            PriorityVariable = priorityVariable;
            SecondaryAddresses = secondaryAddresses;
            Timer = timer;
            TimerVariable = timerVariable;
            TrackOmp = trackOmp;
            TrackOmpVariable = trackOmpVariable;
            TrackPrefixList = trackPrefixList;
            TrackPrefixListVariable = trackPrefixListVariable;
        }
    }
}
