// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetTopologyGroupPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetTopologyGroupPlainArgs Empty = new GetTopologyGroupPlainArgs();

    /**
     * The id of the object
     * 
     */
    @Import(name="id", required=true)
    private String id;

    /**
     * @return The id of the object
     * 
     */
    public String id() {
        return this.id;
    }

    private GetTopologyGroupPlainArgs() {}

    private GetTopologyGroupPlainArgs(GetTopologyGroupPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetTopologyGroupPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetTopologyGroupPlainArgs $;

        public Builder() {
            $ = new GetTopologyGroupPlainArgs();
        }

        public Builder(GetTopologyGroupPlainArgs defaults) {
            $ = new GetTopologyGroupPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param id The id of the object
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            $.id = id;
            return this;
        }

        public GetTopologyGroupPlainArgs build() {
            if ($.id == null) {
                throw new MissingRequiredPropertyException("GetTopologyGroupPlainArgs", "id");
            }
            return $;
        }
    }

}
