// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PolicyObjectUnifiedUrlFilteringState extends com.pulumi.resources.ResourceArgs {

    public static final PolicyObjectUnifiedUrlFilteringState Empty = new PolicyObjectUnifiedUrlFilteringState();

    /**
     * , Attribute conditional on `enableAlerts` equal to `true`
     * 
     */
    @Import(name="alerts")
    private @Nullable Output<List<String>> alerts;

    /**
     * @return , Attribute conditional on `enableAlerts` equal to `true`
     * 
     */
    public Optional<Output<List<String>>> alerts() {
        return Optional.ofNullable(this.alerts);
    }

    /**
     * - Choices: `text`, `redirect-url`
     * 
     */
    @Import(name="blockPageAction")
    private @Nullable Output<String> blockPageAction;

    /**
     * @return - Choices: `text`, `redirect-url`
     * 
     */
    public Optional<Output<String>> blockPageAction() {
        return Optional.ofNullable(this.blockPageAction);
    }

    /**
     * , Attribute conditional on `blockPageAction` equal to `text`
     * 
     */
    @Import(name="blockPageContents")
    private @Nullable Output<String> blockPageContents;

    /**
     * @return , Attribute conditional on `blockPageAction` equal to `text`
     * 
     */
    public Optional<Output<String>> blockPageContents() {
        return Optional.ofNullable(this.blockPageContents);
    }

    /**
     * The description of the Policy_object
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the Policy_object
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="enableAlerts")
    private @Nullable Output<Boolean> enableAlerts;

    public Optional<Output<Boolean>> enableAlerts() {
        return Optional.ofNullable(this.enableAlerts);
    }

    /**
     * Feature Profile ID
     * 
     */
    @Import(name="featureProfileId")
    private @Nullable Output<String> featureProfileId;

    /**
     * @return Feature Profile ID
     * 
     */
    public Optional<Output<String>> featureProfileId() {
        return Optional.ofNullable(this.featureProfileId);
    }

    /**
     * The name of the Policy_object
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the Policy_object
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * , Attribute conditional on `blockPageAction` equal to `redirect-url`
     * 
     */
    @Import(name="redirectUrl")
    private @Nullable Output<String> redirectUrl;

    /**
     * @return , Attribute conditional on `blockPageAction` equal to `redirect-url`
     * 
     */
    public Optional<Output<String>> redirectUrl() {
        return Optional.ofNullable(this.redirectUrl);
    }

    @Import(name="urlAllowListId")
    private @Nullable Output<String> urlAllowListId;

    public Optional<Output<String>> urlAllowListId() {
        return Optional.ofNullable(this.urlAllowListId);
    }

    @Import(name="urlBlockListId")
    private @Nullable Output<String> urlBlockListId;

    public Optional<Output<String>> urlBlockListId() {
        return Optional.ofNullable(this.urlBlockListId);
    }

    /**
     * The version of the Policy_object
     * 
     */
    @Import(name="version")
    private @Nullable Output<Integer> version;

    /**
     * @return The version of the Policy_object
     * 
     */
    public Optional<Output<Integer>> version() {
        return Optional.ofNullable(this.version);
    }

    @Import(name="webCategories")
    private @Nullable Output<List<String>> webCategories;

    public Optional<Output<List<String>>> webCategories() {
        return Optional.ofNullable(this.webCategories);
    }

    /**
     * - Choices: `block`, `allow`
     * 
     */
    @Import(name="webCategoriesAction")
    private @Nullable Output<String> webCategoriesAction;

    /**
     * @return - Choices: `block`, `allow`
     * 
     */
    public Optional<Output<String>> webCategoriesAction() {
        return Optional.ofNullable(this.webCategoriesAction);
    }

    /**
     * - Choices: `high-risk`, `low-risk`, `moderate-risk`, `suspicious`, `trustworthy`
     * 
     */
    @Import(name="webReputation")
    private @Nullable Output<String> webReputation;

    /**
     * @return - Choices: `high-risk`, `low-risk`, `moderate-risk`, `suspicious`, `trustworthy`
     * 
     */
    public Optional<Output<String>> webReputation() {
        return Optional.ofNullable(this.webReputation);
    }

    private PolicyObjectUnifiedUrlFilteringState() {}

    private PolicyObjectUnifiedUrlFilteringState(PolicyObjectUnifiedUrlFilteringState $) {
        this.alerts = $.alerts;
        this.blockPageAction = $.blockPageAction;
        this.blockPageContents = $.blockPageContents;
        this.description = $.description;
        this.enableAlerts = $.enableAlerts;
        this.featureProfileId = $.featureProfileId;
        this.name = $.name;
        this.redirectUrl = $.redirectUrl;
        this.urlAllowListId = $.urlAllowListId;
        this.urlBlockListId = $.urlBlockListId;
        this.version = $.version;
        this.webCategories = $.webCategories;
        this.webCategoriesAction = $.webCategoriesAction;
        this.webReputation = $.webReputation;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PolicyObjectUnifiedUrlFilteringState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PolicyObjectUnifiedUrlFilteringState $;

        public Builder() {
            $ = new PolicyObjectUnifiedUrlFilteringState();
        }

        public Builder(PolicyObjectUnifiedUrlFilteringState defaults) {
            $ = new PolicyObjectUnifiedUrlFilteringState(Objects.requireNonNull(defaults));
        }

        /**
         * @param alerts , Attribute conditional on `enableAlerts` equal to `true`
         * 
         * @return builder
         * 
         */
        public Builder alerts(@Nullable Output<List<String>> alerts) {
            $.alerts = alerts;
            return this;
        }

        /**
         * @param alerts , Attribute conditional on `enableAlerts` equal to `true`
         * 
         * @return builder
         * 
         */
        public Builder alerts(List<String> alerts) {
            return alerts(Output.of(alerts));
        }

        /**
         * @param alerts , Attribute conditional on `enableAlerts` equal to `true`
         * 
         * @return builder
         * 
         */
        public Builder alerts(String... alerts) {
            return alerts(List.of(alerts));
        }

        /**
         * @param blockPageAction - Choices: `text`, `redirect-url`
         * 
         * @return builder
         * 
         */
        public Builder blockPageAction(@Nullable Output<String> blockPageAction) {
            $.blockPageAction = blockPageAction;
            return this;
        }

        /**
         * @param blockPageAction - Choices: `text`, `redirect-url`
         * 
         * @return builder
         * 
         */
        public Builder blockPageAction(String blockPageAction) {
            return blockPageAction(Output.of(blockPageAction));
        }

        /**
         * @param blockPageContents , Attribute conditional on `blockPageAction` equal to `text`
         * 
         * @return builder
         * 
         */
        public Builder blockPageContents(@Nullable Output<String> blockPageContents) {
            $.blockPageContents = blockPageContents;
            return this;
        }

        /**
         * @param blockPageContents , Attribute conditional on `blockPageAction` equal to `text`
         * 
         * @return builder
         * 
         */
        public Builder blockPageContents(String blockPageContents) {
            return blockPageContents(Output.of(blockPageContents));
        }

        /**
         * @param description The description of the Policy_object
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the Policy_object
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder enableAlerts(@Nullable Output<Boolean> enableAlerts) {
            $.enableAlerts = enableAlerts;
            return this;
        }

        public Builder enableAlerts(Boolean enableAlerts) {
            return enableAlerts(Output.of(enableAlerts));
        }

        /**
         * @param featureProfileId Feature Profile ID
         * 
         * @return builder
         * 
         */
        public Builder featureProfileId(@Nullable Output<String> featureProfileId) {
            $.featureProfileId = featureProfileId;
            return this;
        }

        /**
         * @param featureProfileId Feature Profile ID
         * 
         * @return builder
         * 
         */
        public Builder featureProfileId(String featureProfileId) {
            return featureProfileId(Output.of(featureProfileId));
        }

        /**
         * @param name The name of the Policy_object
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the Policy_object
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param redirectUrl , Attribute conditional on `blockPageAction` equal to `redirect-url`
         * 
         * @return builder
         * 
         */
        public Builder redirectUrl(@Nullable Output<String> redirectUrl) {
            $.redirectUrl = redirectUrl;
            return this;
        }

        /**
         * @param redirectUrl , Attribute conditional on `blockPageAction` equal to `redirect-url`
         * 
         * @return builder
         * 
         */
        public Builder redirectUrl(String redirectUrl) {
            return redirectUrl(Output.of(redirectUrl));
        }

        public Builder urlAllowListId(@Nullable Output<String> urlAllowListId) {
            $.urlAllowListId = urlAllowListId;
            return this;
        }

        public Builder urlAllowListId(String urlAllowListId) {
            return urlAllowListId(Output.of(urlAllowListId));
        }

        public Builder urlBlockListId(@Nullable Output<String> urlBlockListId) {
            $.urlBlockListId = urlBlockListId;
            return this;
        }

        public Builder urlBlockListId(String urlBlockListId) {
            return urlBlockListId(Output.of(urlBlockListId));
        }

        /**
         * @param version The version of the Policy_object
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<Integer> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version The version of the Policy_object
         * 
         * @return builder
         * 
         */
        public Builder version(Integer version) {
            return version(Output.of(version));
        }

        public Builder webCategories(@Nullable Output<List<String>> webCategories) {
            $.webCategories = webCategories;
            return this;
        }

        public Builder webCategories(List<String> webCategories) {
            return webCategories(Output.of(webCategories));
        }

        public Builder webCategories(String... webCategories) {
            return webCategories(List.of(webCategories));
        }

        /**
         * @param webCategoriesAction - Choices: `block`, `allow`
         * 
         * @return builder
         * 
         */
        public Builder webCategoriesAction(@Nullable Output<String> webCategoriesAction) {
            $.webCategoriesAction = webCategoriesAction;
            return this;
        }

        /**
         * @param webCategoriesAction - Choices: `block`, `allow`
         * 
         * @return builder
         * 
         */
        public Builder webCategoriesAction(String webCategoriesAction) {
            return webCategoriesAction(Output.of(webCategoriesAction));
        }

        /**
         * @param webReputation - Choices: `high-risk`, `low-risk`, `moderate-risk`, `suspicious`, `trustworthy`
         * 
         * @return builder
         * 
         */
        public Builder webReputation(@Nullable Output<String> webReputation) {
            $.webReputation = webReputation;
            return this;
        }

        /**
         * @param webReputation - Choices: `high-risk`, `low-risk`, `moderate-risk`, `suspicious`, `trustworthy`
         * 
         * @return builder
         * 
         */
        public Builder webReputation(String webReputation) {
            return webReputation(Output.of(webReputation));
        }

        public PolicyObjectUnifiedUrlFilteringState build() {
            return $;
        }
    }

}
