// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PolicyObjectSecurityIdentityListEntryArgs extends com.pulumi.resources.ResourceArgs {

    public static final PolicyObjectSecurityIdentityListEntryArgs Empty = new PolicyObjectSecurityIdentityListEntryArgs();

    @Import(name="user")
    private @Nullable Output<String> user;

    public Optional<Output<String>> user() {
        return Optional.ofNullable(this.user);
    }

    @Import(name="userGroup")
    private @Nullable Output<String> userGroup;

    public Optional<Output<String>> userGroup() {
        return Optional.ofNullable(this.userGroup);
    }

    private PolicyObjectSecurityIdentityListEntryArgs() {}

    private PolicyObjectSecurityIdentityListEntryArgs(PolicyObjectSecurityIdentityListEntryArgs $) {
        this.user = $.user;
        this.userGroup = $.userGroup;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PolicyObjectSecurityIdentityListEntryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PolicyObjectSecurityIdentityListEntryArgs $;

        public Builder() {
            $ = new PolicyObjectSecurityIdentityListEntryArgs();
        }

        public Builder(PolicyObjectSecurityIdentityListEntryArgs defaults) {
            $ = new PolicyObjectSecurityIdentityListEntryArgs(Objects.requireNonNull(defaults));
        }

        public Builder user(@Nullable Output<String> user) {
            $.user = user;
            return this;
        }

        public Builder user(String user) {
            return user(Output.of(user));
        }

        public Builder userGroup(@Nullable Output<String> userGroup) {
            $.userGroup = userGroup;
            return this;
        }

        public Builder userGroup(String userGroup) {
            return userGroup(Output.of(userGroup));
        }

        public PolicyObjectSecurityIdentityListEntryArgs build() {
            return $;
        }
    }

}
