// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.sdwan.inputs.RuleSetPolicyDefinitionRuleArgs;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class RuleSetPolicyDefinitionState extends com.pulumi.resources.ResourceArgs {

    public static final RuleSetPolicyDefinitionState Empty = new RuleSetPolicyDefinitionState();

    /**
     * The description of the policy definition
     * 
     */
    @Import(name="description")
    private @Nullable Output<String> description;

    /**
     * @return The description of the policy definition
     * 
     */
    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * The name of the policy definition
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return The name of the policy definition
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * List of rules
     * 
     */
    @Import(name="rules")
    private @Nullable Output<List<RuleSetPolicyDefinitionRuleArgs>> rules;

    /**
     * @return List of rules
     * 
     */
    public Optional<Output<List<RuleSetPolicyDefinitionRuleArgs>>> rules() {
        return Optional.ofNullable(this.rules);
    }

    /**
     * The version of the object
     * 
     */
    @Import(name="version")
    private @Nullable Output<Integer> version;

    /**
     * @return The version of the object
     * 
     */
    public Optional<Output<Integer>> version() {
        return Optional.ofNullable(this.version);
    }

    private RuleSetPolicyDefinitionState() {}

    private RuleSetPolicyDefinitionState(RuleSetPolicyDefinitionState $) {
        this.description = $.description;
        this.name = $.name;
        this.rules = $.rules;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RuleSetPolicyDefinitionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RuleSetPolicyDefinitionState $;

        public Builder() {
            $ = new RuleSetPolicyDefinitionState();
        }

        public Builder(RuleSetPolicyDefinitionState defaults) {
            $ = new RuleSetPolicyDefinitionState(Objects.requireNonNull(defaults));
        }

        /**
         * @param description The description of the policy definition
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        /**
         * @param description The description of the policy definition
         * 
         * @return builder
         * 
         */
        public Builder description(String description) {
            return description(Output.of(description));
        }

        /**
         * @param name The name of the policy definition
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the policy definition
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param rules List of rules
         * 
         * @return builder
         * 
         */
        public Builder rules(@Nullable Output<List<RuleSetPolicyDefinitionRuleArgs>> rules) {
            $.rules = rules;
            return this;
        }

        /**
         * @param rules List of rules
         * 
         * @return builder
         * 
         */
        public Builder rules(List<RuleSetPolicyDefinitionRuleArgs> rules) {
            return rules(Output.of(rules));
        }

        /**
         * @param rules List of rules
         * 
         * @return builder
         * 
         */
        public Builder rules(RuleSetPolicyDefinitionRuleArgs... rules) {
            return rules(List.of(rules));
        }

        /**
         * @param version The version of the object
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<Integer> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version The version of the object
         * 
         * @return builder
         * 
         */
        public Builder version(Integer version) {
            return version(Output.of(version));
        }

        public RuleSetPolicyDefinitionState build() {
            return $;
        }
    }

}
