// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TransportIpv6TrackerGroupFeatureTrackerElementArgs extends com.pulumi.resources.ResourceArgs {

    public static final TransportIpv6TrackerGroupFeatureTrackerElementArgs Empty = new TransportIpv6TrackerGroupFeatureTrackerElementArgs();

    @Import(name="trackerId")
    private @Nullable Output<String> trackerId;

    public Optional<Output<String>> trackerId() {
        return Optional.ofNullable(this.trackerId);
    }

    private TransportIpv6TrackerGroupFeatureTrackerElementArgs() {}

    private TransportIpv6TrackerGroupFeatureTrackerElementArgs(TransportIpv6TrackerGroupFeatureTrackerElementArgs $) {
        this.trackerId = $.trackerId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TransportIpv6TrackerGroupFeatureTrackerElementArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TransportIpv6TrackerGroupFeatureTrackerElementArgs $;

        public Builder() {
            $ = new TransportIpv6TrackerGroupFeatureTrackerElementArgs();
        }

        public Builder(TransportIpv6TrackerGroupFeatureTrackerElementArgs defaults) {
            $ = new TransportIpv6TrackerGroupFeatureTrackerElementArgs(Objects.requireNonNull(defaults));
        }

        public Builder trackerId(@Nullable Output<String> trackerId) {
            $.trackerId = trackerId;
            return this;
        }

        public Builder trackerId(String trackerId) {
            return trackerId(Output.of(trackerId));
        }

        public TransportIpv6TrackerGroupFeatureTrackerElementArgs build() {
            return $;
        }
    }

}
