// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CiscoVpnFeatureTemplateNatPool {
    /**
     * @return Direction of NAT translation
     *   - Choices: `inside`, `outside`
     * 
     */
    private @Nullable String direction;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String directionVariable;
    /**
     * @return NAT Pool Name, natpool1..31
     *   - Range: `1`-`31`
     * 
     */
    private @Nullable Integer name;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String nameVariable;
    /**
     * @return Indicates if list item is considered optional.
     * 
     */
    private @Nullable Boolean optional;
    /**
     * @return Enable port translation(PAT)
     *   - Default value: `true`
     * 
     */
    private @Nullable Boolean overload;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String overloadVariable;
    /**
     * @return Ending IP address of NAT Pool Prefix Length
     *   - Range: `1`-`32`
     * 
     */
    private @Nullable Integer prefixLength;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String prefixLengthVariable;
    /**
     * @return Ending IP address of NAT pool range
     * 
     */
    private @Nullable String rangeEnd;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String rangeEndVariable;
    /**
     * @return Starting IP address of NAT pool range
     * 
     */
    private @Nullable String rangeStart;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String rangeStartVariable;
    /**
     * @return Add Object/Object Group Tracker
     *   - Range: `1`-`1000`
     * 
     */
    private @Nullable Integer trackerId;
    /**
     * @return Variable name
     * 
     */
    private @Nullable String trackerIdVariable;

    private CiscoVpnFeatureTemplateNatPool() {}
    /**
     * @return Direction of NAT translation
     *   - Choices: `inside`, `outside`
     * 
     */
    public Optional<String> direction() {
        return Optional.ofNullable(this.direction);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> directionVariable() {
        return Optional.ofNullable(this.directionVariable);
    }
    /**
     * @return NAT Pool Name, natpool1..31
     *   - Range: `1`-`31`
     * 
     */
    public Optional<Integer> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> nameVariable() {
        return Optional.ofNullable(this.nameVariable);
    }
    /**
     * @return Indicates if list item is considered optional.
     * 
     */
    public Optional<Boolean> optional() {
        return Optional.ofNullable(this.optional);
    }
    /**
     * @return Enable port translation(PAT)
     *   - Default value: `true`
     * 
     */
    public Optional<Boolean> overload() {
        return Optional.ofNullable(this.overload);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> overloadVariable() {
        return Optional.ofNullable(this.overloadVariable);
    }
    /**
     * @return Ending IP address of NAT Pool Prefix Length
     *   - Range: `1`-`32`
     * 
     */
    public Optional<Integer> prefixLength() {
        return Optional.ofNullable(this.prefixLength);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> prefixLengthVariable() {
        return Optional.ofNullable(this.prefixLengthVariable);
    }
    /**
     * @return Ending IP address of NAT pool range
     * 
     */
    public Optional<String> rangeEnd() {
        return Optional.ofNullable(this.rangeEnd);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> rangeEndVariable() {
        return Optional.ofNullable(this.rangeEndVariable);
    }
    /**
     * @return Starting IP address of NAT pool range
     * 
     */
    public Optional<String> rangeStart() {
        return Optional.ofNullable(this.rangeStart);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> rangeStartVariable() {
        return Optional.ofNullable(this.rangeStartVariable);
    }
    /**
     * @return Add Object/Object Group Tracker
     *   - Range: `1`-`1000`
     * 
     */
    public Optional<Integer> trackerId() {
        return Optional.ofNullable(this.trackerId);
    }
    /**
     * @return Variable name
     * 
     */
    public Optional<String> trackerIdVariable() {
        return Optional.ofNullable(this.trackerIdVariable);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CiscoVpnFeatureTemplateNatPool defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String direction;
        private @Nullable String directionVariable;
        private @Nullable Integer name;
        private @Nullable String nameVariable;
        private @Nullable Boolean optional;
        private @Nullable Boolean overload;
        private @Nullable String overloadVariable;
        private @Nullable Integer prefixLength;
        private @Nullable String prefixLengthVariable;
        private @Nullable String rangeEnd;
        private @Nullable String rangeEndVariable;
        private @Nullable String rangeStart;
        private @Nullable String rangeStartVariable;
        private @Nullable Integer trackerId;
        private @Nullable String trackerIdVariable;
        public Builder() {}
        public Builder(CiscoVpnFeatureTemplateNatPool defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.direction = defaults.direction;
    	      this.directionVariable = defaults.directionVariable;
    	      this.name = defaults.name;
    	      this.nameVariable = defaults.nameVariable;
    	      this.optional = defaults.optional;
    	      this.overload = defaults.overload;
    	      this.overloadVariable = defaults.overloadVariable;
    	      this.prefixLength = defaults.prefixLength;
    	      this.prefixLengthVariable = defaults.prefixLengthVariable;
    	      this.rangeEnd = defaults.rangeEnd;
    	      this.rangeEndVariable = defaults.rangeEndVariable;
    	      this.rangeStart = defaults.rangeStart;
    	      this.rangeStartVariable = defaults.rangeStartVariable;
    	      this.trackerId = defaults.trackerId;
    	      this.trackerIdVariable = defaults.trackerIdVariable;
        }

        @CustomType.Setter
        public Builder direction(@Nullable String direction) {

            this.direction = direction;
            return this;
        }
        @CustomType.Setter
        public Builder directionVariable(@Nullable String directionVariable) {

            this.directionVariable = directionVariable;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable Integer name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder nameVariable(@Nullable String nameVariable) {

            this.nameVariable = nameVariable;
            return this;
        }
        @CustomType.Setter
        public Builder optional(@Nullable Boolean optional) {

            this.optional = optional;
            return this;
        }
        @CustomType.Setter
        public Builder overload(@Nullable Boolean overload) {

            this.overload = overload;
            return this;
        }
        @CustomType.Setter
        public Builder overloadVariable(@Nullable String overloadVariable) {

            this.overloadVariable = overloadVariable;
            return this;
        }
        @CustomType.Setter
        public Builder prefixLength(@Nullable Integer prefixLength) {

            this.prefixLength = prefixLength;
            return this;
        }
        @CustomType.Setter
        public Builder prefixLengthVariable(@Nullable String prefixLengthVariable) {

            this.prefixLengthVariable = prefixLengthVariable;
            return this;
        }
        @CustomType.Setter
        public Builder rangeEnd(@Nullable String rangeEnd) {

            this.rangeEnd = rangeEnd;
            return this;
        }
        @CustomType.Setter
        public Builder rangeEndVariable(@Nullable String rangeEndVariable) {

            this.rangeEndVariable = rangeEndVariable;
            return this;
        }
        @CustomType.Setter
        public Builder rangeStart(@Nullable String rangeStart) {

            this.rangeStart = rangeStart;
            return this;
        }
        @CustomType.Setter
        public Builder rangeStartVariable(@Nullable String rangeStartVariable) {

            this.rangeStartVariable = rangeStartVariable;
            return this;
        }
        @CustomType.Setter
        public Builder trackerId(@Nullable Integer trackerId) {

            this.trackerId = trackerId;
            return this;
        }
        @CustomType.Setter
        public Builder trackerIdVariable(@Nullable String trackerIdVariable) {

            this.trackerIdVariable = trackerIdVariable;
            return this;
        }
        public CiscoVpnFeatureTemplateNatPool build() {
            final var _resultValue = new CiscoVpnFeatureTemplateNatPool();
            _resultValue.direction = direction;
            _resultValue.directionVariable = directionVariable;
            _resultValue.name = name;
            _resultValue.nameVariable = nameVariable;
            _resultValue.optional = optional;
            _resultValue.overload = overload;
            _resultValue.overloadVariable = overloadVariable;
            _resultValue.prefixLength = prefixLength;
            _resultValue.prefixLengthVariable = prefixLengthVariable;
            _resultValue.rangeEnd = rangeEnd;
            _resultValue.rangeEndVariable = rangeEndVariable;
            _resultValue.rangeStart = rangeStart;
            _resultValue.rangeStartVariable = rangeStartVariable;
            _resultValue.trackerId = trackerId;
            _resultValue.trackerIdVariable = trackerIdVariable;
            return _resultValue;
        }
    }
}
