// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress {
    /**
     * @return VRRP Secondary IP address
     * 
     */
    private String ipAddress;
    /**
     * @return Variable name
     * 
     */
    private String ipAddressVariable;
    /**
     * @return Indicates if list item is considered optional.
     * 
     */
    private Boolean optional;

    private GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress() {}
    /**
     * @return VRRP Secondary IP address
     * 
     */
    public String ipAddress() {
        return this.ipAddress;
    }
    /**
     * @return Variable name
     * 
     */
    public String ipAddressVariable() {
        return this.ipAddressVariable;
    }
    /**
     * @return Indicates if list item is considered optional.
     * 
     */
    public Boolean optional() {
        return this.optional;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String ipAddress;
        private String ipAddressVariable;
        private Boolean optional;
        public Builder() {}
        public Builder(GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipAddress = defaults.ipAddress;
    	      this.ipAddressVariable = defaults.ipAddressVariable;
    	      this.optional = defaults.optional;
        }

        @CustomType.Setter
        public Builder ipAddress(String ipAddress) {
            if (ipAddress == null) {
              throw new MissingRequiredPropertyException("GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress", "ipAddress");
            }
            this.ipAddress = ipAddress;
            return this;
        }
        @CustomType.Setter
        public Builder ipAddressVariable(String ipAddressVariable) {
            if (ipAddressVariable == null) {
              throw new MissingRequiredPropertyException("GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress", "ipAddressVariable");
            }
            this.ipAddressVariable = ipAddressVariable;
            return this;
        }
        @CustomType.Setter
        public Builder optional(Boolean optional) {
            if (optional == null) {
              throw new MissingRequiredPropertyException("GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress", "optional");
            }
            this.optional = optional;
            return this;
        }
        public GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress build() {
            final var _resultValue = new GetCiscoVpnInterfaceFeatureTemplateIpv4VrrpIpv4SecondaryAddress();
            _resultValue.ipAddress = ipAddress;
            _resultValue.ipAddressVariable = ipAddressVariable;
            _resultValue.optional = optional;
            return _resultValue;
        }
    }
}
