// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetSystemMrfProfileParcelResult {
    /**
     * @return The description of the profile parcel
     * 
     */
    private String description;
    /**
     * @return Enable migration mode to Multi-Region Fabric
     * 
     */
    private String enableMigrationToMrf;
    /**
     * @return Feature Profile ID
     * 
     */
    private String featureProfileId;
    /**
     * @return The id of the profile parcel
     * 
     */
    private String id;
    /**
     * @return Set BGP community during migration from BGP-core based network
     * 
     */
    private Integer migrationBgpCommunity;
    /**
     * @return The name of the profile parcel
     * 
     */
    private String name;
    /**
     * @return Set region ID
     * 
     */
    private Integer regionId;
    /**
     * @return Set the role for router
     * 
     */
    private String role;
    /**
     * @return Variable name
     * 
     */
    private String roleVariable;
    /**
     * @return Set secondary region ID
     * 
     */
    private Integer secondaryRegionId;
    /**
     * @return Variable name
     * 
     */
    private String secondaryRegionIdVariable;
    /**
     * @return The version of the profile parcel
     * 
     */
    private Integer version;

    private GetSystemMrfProfileParcelResult() {}
    /**
     * @return The description of the profile parcel
     * 
     */
    public String description() {
        return this.description;
    }
    /**
     * @return Enable migration mode to Multi-Region Fabric
     * 
     */
    public String enableMigrationToMrf() {
        return this.enableMigrationToMrf;
    }
    /**
     * @return Feature Profile ID
     * 
     */
    public String featureProfileId() {
        return this.featureProfileId;
    }
    /**
     * @return The id of the profile parcel
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Set BGP community during migration from BGP-core based network
     * 
     */
    public Integer migrationBgpCommunity() {
        return this.migrationBgpCommunity;
    }
    /**
     * @return The name of the profile parcel
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Set region ID
     * 
     */
    public Integer regionId() {
        return this.regionId;
    }
    /**
     * @return Set the role for router
     * 
     */
    public String role() {
        return this.role;
    }
    /**
     * @return Variable name
     * 
     */
    public String roleVariable() {
        return this.roleVariable;
    }
    /**
     * @return Set secondary region ID
     * 
     */
    public Integer secondaryRegionId() {
        return this.secondaryRegionId;
    }
    /**
     * @return Variable name
     * 
     */
    public String secondaryRegionIdVariable() {
        return this.secondaryRegionIdVariable;
    }
    /**
     * @return The version of the profile parcel
     * 
     */
    public Integer version() {
        return this.version;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetSystemMrfProfileParcelResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String description;
        private String enableMigrationToMrf;
        private String featureProfileId;
        private String id;
        private Integer migrationBgpCommunity;
        private String name;
        private Integer regionId;
        private String role;
        private String roleVariable;
        private Integer secondaryRegionId;
        private String secondaryRegionIdVariable;
        private Integer version;
        public Builder() {}
        public Builder(GetSystemMrfProfileParcelResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.description = defaults.description;
    	      this.enableMigrationToMrf = defaults.enableMigrationToMrf;
    	      this.featureProfileId = defaults.featureProfileId;
    	      this.id = defaults.id;
    	      this.migrationBgpCommunity = defaults.migrationBgpCommunity;
    	      this.name = defaults.name;
    	      this.regionId = defaults.regionId;
    	      this.role = defaults.role;
    	      this.roleVariable = defaults.roleVariable;
    	      this.secondaryRegionId = defaults.secondaryRegionId;
    	      this.secondaryRegionIdVariable = defaults.secondaryRegionIdVariable;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder description(String description) {
            if (description == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "description");
            }
            this.description = description;
            return this;
        }
        @CustomType.Setter
        public Builder enableMigrationToMrf(String enableMigrationToMrf) {
            if (enableMigrationToMrf == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "enableMigrationToMrf");
            }
            this.enableMigrationToMrf = enableMigrationToMrf;
            return this;
        }
        @CustomType.Setter
        public Builder featureProfileId(String featureProfileId) {
            if (featureProfileId == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "featureProfileId");
            }
            this.featureProfileId = featureProfileId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder migrationBgpCommunity(Integer migrationBgpCommunity) {
            if (migrationBgpCommunity == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "migrationBgpCommunity");
            }
            this.migrationBgpCommunity = migrationBgpCommunity;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder regionId(Integer regionId) {
            if (regionId == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "regionId");
            }
            this.regionId = regionId;
            return this;
        }
        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder roleVariable(String roleVariable) {
            if (roleVariable == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "roleVariable");
            }
            this.roleVariable = roleVariable;
            return this;
        }
        @CustomType.Setter
        public Builder secondaryRegionId(Integer secondaryRegionId) {
            if (secondaryRegionId == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "secondaryRegionId");
            }
            this.secondaryRegionId = secondaryRegionId;
            return this;
        }
        @CustomType.Setter
        public Builder secondaryRegionIdVariable(String secondaryRegionIdVariable) {
            if (secondaryRegionIdVariable == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "secondaryRegionIdVariable");
            }
            this.secondaryRegionIdVariable = secondaryRegionIdVariable;
            return this;
        }
        @CustomType.Setter
        public Builder version(Integer version) {
            if (version == null) {
              throw new MissingRequiredPropertyException("GetSystemMrfProfileParcelResult", "version");
            }
            this.version = version;
            return this;
        }
        public GetSystemMrfProfileParcelResult build() {
            final var _resultValue = new GetSystemMrfProfileParcelResult();
            _resultValue.description = description;
            _resultValue.enableMigrationToMrf = enableMigrationToMrf;
            _resultValue.featureProfileId = featureProfileId;
            _resultValue.id = id;
            _resultValue.migrationBgpCommunity = migrationBgpCommunity;
            _resultValue.name = name;
            _resultValue.regionId = regionId;
            _resultValue.role = role;
            _resultValue.roleVariable = roleVariable;
            _resultValue.secondaryRegionId = secondaryRegionId;
            _resultValue.secondaryRegionIdVariable = secondaryRegionIdVariable;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
