// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetServiceMulticastFeatureAutoRpDiscovery {
    /**
     * @return Set RP Discovery Interface Name
     * 
     */
    private String interfaceName;
    /**
     * @return Variable name
     * 
     */
    private String interfaceNameVariable;
    /**
     * @return Set RP Discovery Scope
     * 
     */
    private Integer scope;
    /**
     * @return Variable name
     * 
     */
    private String scopeVariable;

    private GetServiceMulticastFeatureAutoRpDiscovery() {}
    /**
     * @return Set RP Discovery Interface Name
     * 
     */
    public String interfaceName() {
        return this.interfaceName;
    }
    /**
     * @return Variable name
     * 
     */
    public String interfaceNameVariable() {
        return this.interfaceNameVariable;
    }
    /**
     * @return Set RP Discovery Scope
     * 
     */
    public Integer scope() {
        return this.scope;
    }
    /**
     * @return Variable name
     * 
     */
    public String scopeVariable() {
        return this.scopeVariable;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServiceMulticastFeatureAutoRpDiscovery defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String interfaceName;
        private String interfaceNameVariable;
        private Integer scope;
        private String scopeVariable;
        public Builder() {}
        public Builder(GetServiceMulticastFeatureAutoRpDiscovery defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.interfaceName = defaults.interfaceName;
    	      this.interfaceNameVariable = defaults.interfaceNameVariable;
    	      this.scope = defaults.scope;
    	      this.scopeVariable = defaults.scopeVariable;
        }

        @CustomType.Setter
        public Builder interfaceName(String interfaceName) {
            if (interfaceName == null) {
              throw new MissingRequiredPropertyException("GetServiceMulticastFeatureAutoRpDiscovery", "interfaceName");
            }
            this.interfaceName = interfaceName;
            return this;
        }
        @CustomType.Setter
        public Builder interfaceNameVariable(String interfaceNameVariable) {
            if (interfaceNameVariable == null) {
              throw new MissingRequiredPropertyException("GetServiceMulticastFeatureAutoRpDiscovery", "interfaceNameVariable");
            }
            this.interfaceNameVariable = interfaceNameVariable;
            return this;
        }
        @CustomType.Setter
        public Builder scope(Integer scope) {
            if (scope == null) {
              throw new MissingRequiredPropertyException("GetServiceMulticastFeatureAutoRpDiscovery", "scope");
            }
            this.scope = scope;
            return this;
        }
        @CustomType.Setter
        public Builder scopeVariable(String scopeVariable) {
            if (scopeVariable == null) {
              throw new MissingRequiredPropertyException("GetServiceMulticastFeatureAutoRpDiscovery", "scopeVariable");
            }
            this.scopeVariable = scopeVariable;
            return this;
        }
        public GetServiceMulticastFeatureAutoRpDiscovery build() {
            final var _resultValue = new GetServiceMulticastFeatureAutoRpDiscovery();
            _resultValue.interfaceName = interfaceName;
            _resultValue.interfaceNameVariable = interfaceNameVariable;
            _resultValue.scope = scope;
            _resultValue.scopeVariable = scopeVariable;
            return _resultValue;
        }
    }
}
