// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.sdwan.outputs.GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterfaceNextHop;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface {
    private String interfaceName;
    /**
     * @return Variable name
     * 
     */
    private String interfaceNameVariable;
    private List<GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterfaceNextHop> nextHops;

    private GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface() {}
    public String interfaceName() {
        return this.interfaceName;
    }
    /**
     * @return Variable name
     * 
     */
    public String interfaceNameVariable() {
        return this.interfaceNameVariable;
    }
    public List<GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterfaceNextHop> nextHops() {
        return this.nextHops;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String interfaceName;
        private String interfaceNameVariable;
        private List<GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterfaceNextHop> nextHops;
        public Builder() {}
        public Builder(GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.interfaceName = defaults.interfaceName;
    	      this.interfaceNameVariable = defaults.interfaceNameVariable;
    	      this.nextHops = defaults.nextHops;
        }

        @CustomType.Setter
        public Builder interfaceName(String interfaceName) {
            if (interfaceName == null) {
              throw new MissingRequiredPropertyException("GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface", "interfaceName");
            }
            this.interfaceName = interfaceName;
            return this;
        }
        @CustomType.Setter
        public Builder interfaceNameVariable(String interfaceNameVariable) {
            if (interfaceNameVariable == null) {
              throw new MissingRequiredPropertyException("GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface", "interfaceNameVariable");
            }
            this.interfaceNameVariable = interfaceNameVariable;
            return this;
        }
        @CustomType.Setter
        public Builder nextHops(List<GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterfaceNextHop> nextHops) {
            if (nextHops == null) {
              throw new MissingRequiredPropertyException("GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface", "nextHops");
            }
            this.nextHops = nextHops;
            return this;
        }
        public Builder nextHops(GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterfaceNextHop... nextHops) {
            return nextHops(List.of(nextHops));
        }
        public GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface build() {
            final var _resultValue = new GetServiceLanVpnFeatureIpv6StaticRouteIpv6StaticRouteInterface();
            _resultValue.interfaceName = interfaceName;
            _resultValue.interfaceNameVariable = interfaceNameVariable;
            _resultValue.nextHops = nextHops;
            return _resultValue;
        }
    }
}
