// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class PolicyObjectIpv6PrefixListEntry {
    /**
     * @return IPv6 prefix length with ge range operator
     *   - Range: `1`-`128`
     * 
     */
    private @Nullable Integer ge;
    /**
     * @return IPv6 address
     * 
     */
    private @Nullable String ipv6Address;
    /**
     * @return IPv6 prefix length
     *   - Range: `0`-`128`
     * 
     */
    private @Nullable Integer ipv6PrefixLength;
    /**
     * @return IPv6 prefix length with le range operator
     *   - Range: `1`-`128`
     * 
     */
    private @Nullable Integer le;

    private PolicyObjectIpv6PrefixListEntry() {}
    /**
     * @return IPv6 prefix length with ge range operator
     *   - Range: `1`-`128`
     * 
     */
    public Optional<Integer> ge() {
        return Optional.ofNullable(this.ge);
    }
    /**
     * @return IPv6 address
     * 
     */
    public Optional<String> ipv6Address() {
        return Optional.ofNullable(this.ipv6Address);
    }
    /**
     * @return IPv6 prefix length
     *   - Range: `0`-`128`
     * 
     */
    public Optional<Integer> ipv6PrefixLength() {
        return Optional.ofNullable(this.ipv6PrefixLength);
    }
    /**
     * @return IPv6 prefix length with le range operator
     *   - Range: `1`-`128`
     * 
     */
    public Optional<Integer> le() {
        return Optional.ofNullable(this.le);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(PolicyObjectIpv6PrefixListEntry defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Integer ge;
        private @Nullable String ipv6Address;
        private @Nullable Integer ipv6PrefixLength;
        private @Nullable Integer le;
        public Builder() {}
        public Builder(PolicyObjectIpv6PrefixListEntry defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ge = defaults.ge;
    	      this.ipv6Address = defaults.ipv6Address;
    	      this.ipv6PrefixLength = defaults.ipv6PrefixLength;
    	      this.le = defaults.le;
        }

        @CustomType.Setter
        public Builder ge(@Nullable Integer ge) {

            this.ge = ge;
            return this;
        }
        @CustomType.Setter
        public Builder ipv6Address(@Nullable String ipv6Address) {

            this.ipv6Address = ipv6Address;
            return this;
        }
        @CustomType.Setter
        public Builder ipv6PrefixLength(@Nullable Integer ipv6PrefixLength) {

            this.ipv6PrefixLength = ipv6PrefixLength;
            return this;
        }
        @CustomType.Setter
        public Builder le(@Nullable Integer le) {

            this.le = le;
            return this;
        }
        public PolicyObjectIpv6PrefixListEntry build() {
            final var _resultValue = new PolicyObjectIpv6PrefixListEntry();
            _resultValue.ge = ge;
            _resultValue.ipv6Address = ipv6Address;
            _resultValue.ipv6PrefixLength = ipv6PrefixLength;
            _resultValue.le = le;
            return _resultValue;
        }
    }
}
