// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sdwan.LocalizedPolicyArgs;
import com.pulumi.sdwan.Utilities;
import com.pulumi.sdwan.inputs.LocalizedPolicyState;
import com.pulumi.sdwan.outputs.LocalizedPolicyDefinition;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage a Localized Policy .
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sdwan.LocalizedPolicy;
 * import com.pulumi.sdwan.LocalizedPolicyArgs;
 * import com.pulumi.sdwan.inputs.LocalizedPolicyDefinitionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new LocalizedPolicy("example", LocalizedPolicyArgs.builder()
 *             .name("Example")
 *             .description("My description")
 *             .flowVisibilityIpv4(true)
 *             .flowVisibilityIpv6(true)
 *             .applicationVisibilityIpv4(true)
 *             .applicationVisibilityIpv6(true)
 *             .cloudQos(true)
 *             .cloudQosServiceSide(true)
 *             .implicitAclLogging(true)
 *             .logFrequency(1000)
 *             .ipv4VisibilityCacheEntries(1000)
 *             .ipv6VisibilityCacheEntries(1000)
 *             .definitions(LocalizedPolicyDefinitionArgs.builder()
 *                 .id("2081c2f4-3f9f-4fee-8078-dcc8904e368d")
 *                 .type("acl")
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * The `pulumi import` command can be used, for example:
 * 
 * ```sh
 * $ pulumi import sdwan:index/localizedPolicy:LocalizedPolicy example &#34;f6b2c44c-693c-4763-b010-895aa3d236bd&#34;
 * ```
 * 
 */
@ResourceType(type="sdwan:index/localizedPolicy:LocalizedPolicy")
public class LocalizedPolicy extends com.pulumi.resources.CustomResource {
    /**
     * IPv4 application visibility - Default value: `true`
     * 
     */
    @Export(name="applicationVisibilityIpv4", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> applicationVisibilityIpv4;

    /**
     * @return IPv4 application visibility - Default value: `true`
     * 
     */
    public Output<Boolean> applicationVisibilityIpv4() {
        return this.applicationVisibilityIpv4;
    }
    /**
     * IPv6 application visibility - Default value: `true`
     * 
     */
    @Export(name="applicationVisibilityIpv6", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> applicationVisibilityIpv6;

    /**
     * @return IPv6 application visibility - Default value: `true`
     * 
     */
    public Output<Boolean> applicationVisibilityIpv6() {
        return this.applicationVisibilityIpv6;
    }
    /**
     * Cloud QoS - Default value: `true`
     * 
     */
    @Export(name="cloudQos", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> cloudQos;

    /**
     * @return Cloud QoS - Default value: `true`
     * 
     */
    public Output<Boolean> cloudQos() {
        return this.cloudQos;
    }
    /**
     * Cloud QoS service side - Default value: `true`
     * 
     */
    @Export(name="cloudQosServiceSide", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> cloudQosServiceSide;

    /**
     * @return Cloud QoS service side - Default value: `true`
     * 
     */
    public Output<Boolean> cloudQosServiceSide() {
        return this.cloudQosServiceSide;
    }
    /**
     * List of policy definitions
     * 
     */
    @Export(name="definitions", refs={List.class,LocalizedPolicyDefinition.class}, tree="[0,1]")
    private Output</* @Nullable */ List<LocalizedPolicyDefinition>> definitions;

    /**
     * @return List of policy definitions
     * 
     */
    public Output<Optional<List<LocalizedPolicyDefinition>>> definitions() {
        return Codegen.optional(this.definitions);
    }
    /**
     * The description of the localized policy
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return The description of the localized policy
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * IPv4 flow visibility - Default value: `true`
     * 
     */
    @Export(name="flowVisibilityIpv4", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> flowVisibilityIpv4;

    /**
     * @return IPv4 flow visibility - Default value: `true`
     * 
     */
    public Output<Boolean> flowVisibilityIpv4() {
        return this.flowVisibilityIpv4;
    }
    /**
     * IPv6 flow visibility - Default value: `true`
     * 
     */
    @Export(name="flowVisibilityIpv6", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> flowVisibilityIpv6;

    /**
     * @return IPv6 flow visibility - Default value: `true`
     * 
     */
    public Output<Boolean> flowVisibilityIpv6() {
        return this.flowVisibilityIpv6;
    }
    /**
     * Implicit ACL logging - Default value: `true`
     * 
     */
    @Export(name="implicitAclLogging", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> implicitAclLogging;

    /**
     * @return Implicit ACL logging - Default value: `true`
     * 
     */
    public Output<Boolean> implicitAclLogging() {
        return this.implicitAclLogging;
    }
    /**
     * IPv4 visibility cache entries - Range: `16`-`2000000`
     * 
     */
    @Export(name="ipv4VisibilityCacheEntries", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> ipv4VisibilityCacheEntries;

    /**
     * @return IPv4 visibility cache entries - Range: `16`-`2000000`
     * 
     */
    public Output<Optional<Integer>> ipv4VisibilityCacheEntries() {
        return Codegen.optional(this.ipv4VisibilityCacheEntries);
    }
    /**
     * IPv6 visibility cache entries - Range: `16`-`2000000`
     * 
     */
    @Export(name="ipv6VisibilityCacheEntries", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> ipv6VisibilityCacheEntries;

    /**
     * @return IPv6 visibility cache entries - Range: `16`-`2000000`
     * 
     */
    public Output<Optional<Integer>> ipv6VisibilityCacheEntries() {
        return Codegen.optional(this.ipv6VisibilityCacheEntries);
    }
    /**
     * Log frequency - Range: `1`-`2147483647`
     * 
     */
    @Export(name="logFrequency", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> logFrequency;

    /**
     * @return Log frequency - Range: `1`-`2147483647`
     * 
     */
    public Output<Optional<Integer>> logFrequency() {
        return Codegen.optional(this.logFrequency);
    }
    /**
     * The name of the localized policy
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the localized policy
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * The version of the object
     * 
     */
    @Export(name="version", refs={Integer.class}, tree="[0]")
    private Output<Integer> version;

    /**
     * @return The version of the object
     * 
     */
    public Output<Integer> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public LocalizedPolicy(java.lang.String name) {
        this(name, LocalizedPolicyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public LocalizedPolicy(java.lang.String name, LocalizedPolicyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public LocalizedPolicy(java.lang.String name, LocalizedPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sdwan:index/localizedPolicy:LocalizedPolicy", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private LocalizedPolicy(java.lang.String name, Output<java.lang.String> id, @Nullable LocalizedPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sdwan:index/localizedPolicy:LocalizedPolicy", name, state, makeResourceOptions(options, id), false);
    }

    private static LocalizedPolicyArgs makeArgs(LocalizedPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? LocalizedPolicyArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static LocalizedPolicy get(java.lang.String name, Output<java.lang.String> id, @Nullable LocalizedPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new LocalizedPolicy(name, id, state, options);
    }
}
