// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sdwan.SecurityPolicyArgs;
import com.pulumi.sdwan.Utilities;
import com.pulumi.sdwan.inputs.SecurityPolicyState;
import com.pulumi.sdwan.outputs.SecurityPolicyDefinition;
import com.pulumi.sdwan.outputs.SecurityPolicyLogging;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * This resource can manage a Security Policy .
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.sdwan.SecurityPolicy;
 * import com.pulumi.sdwan.SecurityPolicyArgs;
 * import com.pulumi.sdwan.inputs.SecurityPolicyDefinitionArgs;
 * import com.pulumi.sdwan.inputs.SecurityPolicyLoggingArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var example = new SecurityPolicy("example", SecurityPolicyArgs.builder()
 *             .name("Example")
 *             .description("Example")
 *             .mode("security")
 *             .useCase("custom")
 *             .definitions(SecurityPolicyDefinitionArgs.builder()
 *                 .id("7d299c34-981c-4fb3-9167-6be44ab1691f")
 *                 .type("urlFiltering")
 *                 .build())
 *             .failureMode("close")
 *             .loggings(SecurityPolicyLoggingArgs.builder()
 *                 .external_syslog_server_ip("10.0.0.1")
 *                 .external_syslog_server_vpn("123")
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * ```sh
 * $ pulumi import sdwan:index/securityPolicy:SecurityPolicy example &#34;f6b2c44c-693c-4763-b010-895aa3d236bd&#34;
 * ```
 * 
 */
@ResourceType(type="sdwan:index/securityPolicy:SecurityPolicy")
public class SecurityPolicy extends com.pulumi.resources.CustomResource {
    /**
     * Audit trail - Choices: `on`, `off`
     * 
     */
    @Export(name="auditTrail", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> auditTrail;

    /**
     * @return Audit trail - Choices: `on`, `off`
     * 
     */
    public Output<Optional<String>> auditTrail() {
        return Codegen.optional(this.auditTrail);
    }
    /**
     * List of policy definitions
     * 
     */
    @Export(name="definitions", refs={List.class,SecurityPolicyDefinition.class}, tree="[0,1]")
    private Output<List<SecurityPolicyDefinition>> definitions;

    /**
     * @return List of policy definitions
     * 
     */
    public Output<List<SecurityPolicyDefinition>> definitions() {
        return this.definitions;
    }
    /**
     * The description of the security policy
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return The description of the security policy
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * Bypass firewall policy and allow all Internet traffic to/from VPN 0 - Choices: `allow`, `deny`
     * 
     */
    @Export(name="directInternetApplications", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> directInternetApplications;

    /**
     * @return Bypass firewall policy and allow all Internet traffic to/from VPN 0 - Choices: `allow`, `deny`
     * 
     */
    public Output<Optional<String>> directInternetApplications() {
        return Codegen.optional(this.directInternetApplications);
    }
    /**
     * Failure mode - Choices: `open`, `close` - Default value: `open`
     * 
     */
    @Export(name="failureMode", refs={String.class}, tree="[0]")
    private Output<String> failureMode;

    /**
     * @return Failure mode - Choices: `open`, `close` - Default value: `open`
     * 
     */
    public Output<String> failureMode() {
        return this.failureMode;
    }
    /**
     * High Speed Logging Server IP
     * 
     */
    @Export(name="highSpeedLoggingServerIp", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> highSpeedLoggingServerIp;

    /**
     * @return High Speed Logging Server IP
     * 
     */
    public Output<Optional<String>> highSpeedLoggingServerIp() {
        return Codegen.optional(this.highSpeedLoggingServerIp);
    }
    /**
     * High Speed Logging Port
     * 
     */
    @Export(name="highSpeedLoggingServerPort", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> highSpeedLoggingServerPort;

    /**
     * @return High Speed Logging Port
     * 
     */
    public Output<Optional<String>> highSpeedLoggingServerPort() {
        return Codegen.optional(this.highSpeedLoggingServerPort);
    }
    /**
     * High Speed Logging VPN
     * 
     */
    @Export(name="highSpeedLoggingVpn", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> highSpeedLoggingVpn;

    /**
     * @return High Speed Logging VPN
     * 
     */
    public Output<Optional<String>> highSpeedLoggingVpn() {
        return Codegen.optional(this.highSpeedLoggingVpn);
    }
    @Export(name="loggings", refs={List.class,SecurityPolicyLogging.class}, tree="[0,1]")
    private Output</* @Nullable */ List<SecurityPolicyLogging>> loggings;

    public Output<Optional<List<SecurityPolicyLogging>>> loggings() {
        return Codegen.optional(this.loggings);
    }
    /**
     * Match Statistics per-filter - Choices: `on`, `off`
     * 
     */
    @Export(name="matchStatisticsPerFilter", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> matchStatisticsPerFilter;

    /**
     * @return Match Statistics per-filter - Choices: `on`, `off`
     * 
     */
    public Output<Optional<String>> matchStatisticsPerFilter() {
        return Codegen.optional(this.matchStatisticsPerFilter);
    }
    /**
     * The policy mode - Choices: `security`, `unified` - Default value: `security`
     * 
     */
    @Export(name="mode", refs={String.class}, tree="[0]")
    private Output<String> mode;

    /**
     * @return The policy mode - Choices: `security`, `unified` - Default value: `security`
     * 
     */
    public Output<String> mode() {
        return this.mode;
    }
    /**
     * The name of the security policy
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the security policy
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * TCP SYN Flood Limit, value from 1 to 4294967295
     * 
     */
    @Export(name="tcpSynFloodLimit", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tcpSynFloodLimit;

    /**
     * @return TCP SYN Flood Limit, value from 1 to 4294967295
     * 
     */
    public Output<Optional<String>> tcpSynFloodLimit() {
        return Codegen.optional(this.tcpSynFloodLimit);
    }
    /**
     * The use case of the security policy - Choices: `custom`, `compliance`, `guestAccess`, `directCloudAccess`,
     * `directInternetAccess`, `directCloudAccess` - Default value: `custom`
     * 
     */
    @Export(name="useCase", refs={String.class}, tree="[0]")
    private Output<String> useCase;

    /**
     * @return The use case of the security policy - Choices: `custom`, `compliance`, `guestAccess`, `directCloudAccess`,
     * `directInternetAccess`, `directCloudAccess` - Default value: `custom`
     * 
     */
    public Output<String> useCase() {
        return this.useCase;
    }
    /**
     * The version of the object
     * 
     */
    @Export(name="version", refs={Integer.class}, tree="[0]")
    private Output<Integer> version;

    /**
     * @return The version of the object
     * 
     */
    public Output<Integer> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SecurityPolicy(String name) {
        this(name, SecurityPolicyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SecurityPolicy(String name, SecurityPolicyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SecurityPolicy(String name, SecurityPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sdwan:index/securityPolicy:SecurityPolicy", name, args == null ? SecurityPolicyArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private SecurityPolicy(String name, Output<String> id, @Nullable SecurityPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sdwan:index/securityPolicy:SecurityPolicy", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SecurityPolicy get(String name, Output<String> id, @Nullable SecurityPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SecurityPolicy(name, id, state, options);
    }
}
