// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.sdwan;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.sdwan.Utilities;
import com.pulumi.sdwan.VpnMembershipPolicyDefinitionArgs;
import com.pulumi.sdwan.inputs.VpnMembershipPolicyDefinitionState;
import com.pulumi.sdwan.outputs.VpnMembershipPolicyDefinitionSite;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * This resource can manage a VPN Membership Policy Definition .
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * The `pulumi import` command can be used, for example:
 * 
 * ```sh
 * $ pulumi import sdwan:index/vpnMembershipPolicyDefinition:VpnMembershipPolicyDefinition example &#34;f6b2c44c-693c-4763-b010-895aa3d236bd&#34;
 * ```
 * 
 */
@ResourceType(type="sdwan:index/vpnMembershipPolicyDefinition:VpnMembershipPolicyDefinition")
public class VpnMembershipPolicyDefinition extends com.pulumi.resources.CustomResource {
    /**
     * The description of the policy definition
     * 
     */
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output<String> description;

    /**
     * @return The description of the policy definition
     * 
     */
    public Output<String> description() {
        return this.description;
    }
    /**
     * The name of the policy definition
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The name of the policy definition
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * List of sites
     * 
     */
    @Export(name="sites", refs={List.class,VpnMembershipPolicyDefinitionSite.class}, tree="[0,1]")
    private Output<List<VpnMembershipPolicyDefinitionSite>> sites;

    /**
     * @return List of sites
     * 
     */
    public Output<List<VpnMembershipPolicyDefinitionSite>> sites() {
        return this.sites;
    }
    /**
     * Type
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return Type
     * 
     */
    public Output<String> type() {
        return this.type;
    }
    /**
     * The version of the object
     * 
     */
    @Export(name="version", refs={Integer.class}, tree="[0]")
    private Output<Integer> version;

    /**
     * @return The version of the object
     * 
     */
    public Output<Integer> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public VpnMembershipPolicyDefinition(java.lang.String name) {
        this(name, VpnMembershipPolicyDefinitionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public VpnMembershipPolicyDefinition(java.lang.String name, VpnMembershipPolicyDefinitionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public VpnMembershipPolicyDefinition(java.lang.String name, VpnMembershipPolicyDefinitionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sdwan:index/vpnMembershipPolicyDefinition:VpnMembershipPolicyDefinition", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private VpnMembershipPolicyDefinition(java.lang.String name, Output<java.lang.String> id, @Nullable VpnMembershipPolicyDefinitionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("sdwan:index/vpnMembershipPolicyDefinition:VpnMembershipPolicyDefinition", name, state, makeResourceOptions(options, id), false);
    }

    private static VpnMembershipPolicyDefinitionArgs makeArgs(VpnMembershipPolicyDefinitionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? VpnMembershipPolicyDefinitionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static VpnMembershipPolicyDefinition get(java.lang.String name, Output<java.lang.String> id, @Nullable VpnMembershipPolicyDefinitionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new VpnMembershipPolicyDefinition(name, id, state, options);
    }
}
