// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sdwan

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-sdwan/sdk/go/sdwan/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source can read the Zone Based Firewall Policy Definition .
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-sdwan/sdk/go/sdwan"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := sdwan.LookupZoneBasedFirewallPolicyDefinition(ctx, &sdwan.LookupZoneBasedFirewallPolicyDefinitionArgs{
//				Id: "f6b2c44c-693c-4763-b010-895aa3d236bd",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupZoneBasedFirewallPolicyDefinition(ctx *pulumi.Context, args *LookupZoneBasedFirewallPolicyDefinitionArgs, opts ...pulumi.InvokeOption) (*LookupZoneBasedFirewallPolicyDefinitionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupZoneBasedFirewallPolicyDefinitionResult
	err := ctx.Invoke("sdwan:index/getZoneBasedFirewallPolicyDefinition:getZoneBasedFirewallPolicyDefinition", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZoneBasedFirewallPolicyDefinition.
type LookupZoneBasedFirewallPolicyDefinitionArgs struct {
	// The id of the object
	Id string `pulumi:"id"`
}

// A collection of values returned by getZoneBasedFirewallPolicyDefinition.
type LookupZoneBasedFirewallPolicyDefinitionResult struct {
	ApplyZonePairs []GetZoneBasedFirewallPolicyDefinitionApplyZonePair `pulumi:"applyZonePairs"`
	// Default Action
	DefaultAction string `pulumi:"defaultAction"`
	// The description of the policy definition
	Description string `pulumi:"description"`
	// The id of the object
	Id string `pulumi:"id"`
	// The policy mode
	Mode string `pulumi:"mode"`
	// The name of the policy definition
	Name  string                                     `pulumi:"name"`
	Rules []GetZoneBasedFirewallPolicyDefinitionRule `pulumi:"rules"`
	// The version of the object
	Version int `pulumi:"version"`
}

func LookupZoneBasedFirewallPolicyDefinitionOutput(ctx *pulumi.Context, args LookupZoneBasedFirewallPolicyDefinitionOutputArgs, opts ...pulumi.InvokeOption) LookupZoneBasedFirewallPolicyDefinitionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupZoneBasedFirewallPolicyDefinitionResultOutput, error) {
			args := v.(LookupZoneBasedFirewallPolicyDefinitionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("sdwan:index/getZoneBasedFirewallPolicyDefinition:getZoneBasedFirewallPolicyDefinition", args, LookupZoneBasedFirewallPolicyDefinitionResultOutput{}, options).(LookupZoneBasedFirewallPolicyDefinitionResultOutput), nil
		}).(LookupZoneBasedFirewallPolicyDefinitionResultOutput)
}

// A collection of arguments for invoking getZoneBasedFirewallPolicyDefinition.
type LookupZoneBasedFirewallPolicyDefinitionOutputArgs struct {
	// The id of the object
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupZoneBasedFirewallPolicyDefinitionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZoneBasedFirewallPolicyDefinitionArgs)(nil)).Elem()
}

// A collection of values returned by getZoneBasedFirewallPolicyDefinition.
type LookupZoneBasedFirewallPolicyDefinitionResultOutput struct{ *pulumi.OutputState }

func (LookupZoneBasedFirewallPolicyDefinitionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupZoneBasedFirewallPolicyDefinitionResult)(nil)).Elem()
}

func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) ToLookupZoneBasedFirewallPolicyDefinitionResultOutput() LookupZoneBasedFirewallPolicyDefinitionResultOutput {
	return o
}

func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) ToLookupZoneBasedFirewallPolicyDefinitionResultOutputWithContext(ctx context.Context) LookupZoneBasedFirewallPolicyDefinitionResultOutput {
	return o
}

func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) ApplyZonePairs() GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) []GetZoneBasedFirewallPolicyDefinitionApplyZonePair {
		return v.ApplyZonePairs
	}).(GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput)
}

// Default Action
func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) DefaultAction() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) string { return v.DefaultAction }).(pulumi.StringOutput)
}

// The description of the policy definition
func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) string { return v.Description }).(pulumi.StringOutput)
}

// The id of the object
func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) string { return v.Id }).(pulumi.StringOutput)
}

// The policy mode
func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) Mode() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) string { return v.Mode }).(pulumi.StringOutput)
}

// The name of the policy definition
func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) Rules() GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) []GetZoneBasedFirewallPolicyDefinitionRule {
		return v.Rules
	}).(GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput)
}

// The version of the object
func (o LookupZoneBasedFirewallPolicyDefinitionResultOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v LookupZoneBasedFirewallPolicyDefinitionResult) int { return v.Version }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupZoneBasedFirewallPolicyDefinitionResultOutput{})
}
