// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package sdwan

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-sdwan/sdk/go/sdwan/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList struct {
	// Name of access list
	AclName string `pulumi:"aclName"`
	// Variable name
	AclNameVariable string `pulumi:"aclNameVariable"`
	// Direction
	Direction string `pulumi:"direction"`
	// Indicates if list item is considered optional.
	Optional bool `pulumi:"optional"`
}

// GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListInput is an input type that accepts GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs and GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput values.
// You can construct a concrete instance of `GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListInput` via:
//
//	GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs{...}
type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListInput interface {
	pulumi.Input

	ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput() GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput
	ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutputWithContext(context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput
}

type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs struct {
	// Name of access list
	AclName pulumi.StringInput `pulumi:"aclName"`
	// Variable name
	AclNameVariable pulumi.StringInput `pulumi:"aclNameVariable"`
	// Direction
	Direction pulumi.StringInput `pulumi:"direction"`
	// Indicates if list item is considered optional.
	Optional pulumi.BoolInput `pulumi:"optional"`
}

func (GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList)(nil)).Elem()
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput() GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput {
	return i.ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutputWithContext(context.Background())
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput)
}

// GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayInput is an input type that accepts GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray and GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput values.
// You can construct a concrete instance of `GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayInput` via:
//
//	GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray{ GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs{...} }
type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayInput interface {
	pulumi.Input

	ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput() GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput
	ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutputWithContext(context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput
}

type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray []GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListInput

func (GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList)(nil)).Elem()
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput() GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput {
	return i.ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutputWithContext(context.Background())
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput)
}

type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput struct{ *pulumi.OutputState }

func (GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList)(nil)).Elem()
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput() GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput {
	return o
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput {
	return o
}

// Name of access list
func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) AclName() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList) string { return v.AclName }).(pulumi.StringOutput)
}

// Variable name
func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) AclNameVariable() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList) string { return v.AclNameVariable }).(pulumi.StringOutput)
}

// Direction
func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) Direction() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList) string { return v.Direction }).(pulumi.StringOutput)
}

// Indicates if list item is considered optional.
func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput) Optional() pulumi.BoolOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList) bool { return v.Optional }).(pulumi.BoolOutput)
}

type GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput struct{ *pulumi.OutputState }

func (GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList)(nil)).Elem()
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput() GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput {
	return o
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput {
	return o
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput) Index(i pulumi.IntInput) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList {
		return vs[0].([]GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessList)[vs[1].(int)]
	}).(GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput)
}

type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation struct {
	// Encapsulation
	Encapsulation string `pulumi:"encapsulation"`
	// Indicates if list item is considered optional.
	Optional bool `pulumi:"optional"`
	// Set preference for TLOC
	Preference int `pulumi:"preference"`
	// Variable name
	PreferenceVariable string `pulumi:"preferenceVariable"`
	// Set weight for TLOC
	Weight int `pulumi:"weight"`
	// Variable name
	WeightVariable string `pulumi:"weightVariable"`
}

// GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationInput is an input type that accepts GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs and GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput values.
// You can construct a concrete instance of `GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationInput` via:
//
//	GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs{...}
type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationInput interface {
	pulumi.Input

	ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput() GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput
	ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutputWithContext(context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput
}

type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs struct {
	// Encapsulation
	Encapsulation pulumi.StringInput `pulumi:"encapsulation"`
	// Indicates if list item is considered optional.
	Optional pulumi.BoolInput `pulumi:"optional"`
	// Set preference for TLOC
	Preference pulumi.IntInput `pulumi:"preference"`
	// Variable name
	PreferenceVariable pulumi.StringInput `pulumi:"preferenceVariable"`
	// Set weight for TLOC
	Weight pulumi.IntInput `pulumi:"weight"`
	// Variable name
	WeightVariable pulumi.StringInput `pulumi:"weightVariable"`
}

func (GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation)(nil)).Elem()
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput() GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput {
	return i.ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutputWithContext(context.Background())
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput)
}

// GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayInput is an input type that accepts GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray and GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput values.
// You can construct a concrete instance of `GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayInput` via:
//
//	GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray{ GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs{...} }
type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayInput interface {
	pulumi.Input

	ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput() GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput
	ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutputWithContext(context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput
}

type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray []GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationInput

func (GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation)(nil)).Elem()
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput() GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput {
	return i.ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutputWithContext(context.Background())
}

func (i GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput)
}

type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput struct{ *pulumi.OutputState }

func (GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation)(nil)).Elem()
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput() GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput {
	return o
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput {
	return o
}

// Encapsulation
func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) Encapsulation() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation) string {
		return v.Encapsulation
	}).(pulumi.StringOutput)
}

// Indicates if list item is considered optional.
func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) Optional() pulumi.BoolOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation) bool { return v.Optional }).(pulumi.BoolOutput)
}

// Set preference for TLOC
func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) Preference() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation) int { return v.Preference }).(pulumi.IntOutput)
}

// Variable name
func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) PreferenceVariable() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation) string {
		return v.PreferenceVariable
	}).(pulumi.StringOutput)
}

// Set weight for TLOC
func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) Weight() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation) int { return v.Weight }).(pulumi.IntOutput)
}

// Variable name
func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput) WeightVariable() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation) string {
		return v.WeightVariable
	}).(pulumi.StringOutput)
}

type GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput struct{ *pulumi.OutputState }

func (GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation)(nil)).Elem()
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput() GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput {
	return o
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput) ToGetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutputWithContext(ctx context.Context) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput {
	return o
}

func (o GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput) Index(i pulumi.IntInput) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation {
		return vs[0].([]GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulation)[vs[1].(int)]
	}).(GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput)
}

type GetVpnListPolicyObjectEntry struct {
	// VPN ID or range of VPN IDs e.g., `100` or `200-300`
	VpnId string `pulumi:"vpnId"`
}

// GetVpnListPolicyObjectEntryInput is an input type that accepts GetVpnListPolicyObjectEntryArgs and GetVpnListPolicyObjectEntryOutput values.
// You can construct a concrete instance of `GetVpnListPolicyObjectEntryInput` via:
//
//	GetVpnListPolicyObjectEntryArgs{...}
type GetVpnListPolicyObjectEntryInput interface {
	pulumi.Input

	ToGetVpnListPolicyObjectEntryOutput() GetVpnListPolicyObjectEntryOutput
	ToGetVpnListPolicyObjectEntryOutputWithContext(context.Context) GetVpnListPolicyObjectEntryOutput
}

type GetVpnListPolicyObjectEntryArgs struct {
	// VPN ID or range of VPN IDs e.g., `100` or `200-300`
	VpnId pulumi.StringInput `pulumi:"vpnId"`
}

func (GetVpnListPolicyObjectEntryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnListPolicyObjectEntry)(nil)).Elem()
}

func (i GetVpnListPolicyObjectEntryArgs) ToGetVpnListPolicyObjectEntryOutput() GetVpnListPolicyObjectEntryOutput {
	return i.ToGetVpnListPolicyObjectEntryOutputWithContext(context.Background())
}

func (i GetVpnListPolicyObjectEntryArgs) ToGetVpnListPolicyObjectEntryOutputWithContext(ctx context.Context) GetVpnListPolicyObjectEntryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnListPolicyObjectEntryOutput)
}

// GetVpnListPolicyObjectEntryArrayInput is an input type that accepts GetVpnListPolicyObjectEntryArray and GetVpnListPolicyObjectEntryArrayOutput values.
// You can construct a concrete instance of `GetVpnListPolicyObjectEntryArrayInput` via:
//
//	GetVpnListPolicyObjectEntryArray{ GetVpnListPolicyObjectEntryArgs{...} }
type GetVpnListPolicyObjectEntryArrayInput interface {
	pulumi.Input

	ToGetVpnListPolicyObjectEntryArrayOutput() GetVpnListPolicyObjectEntryArrayOutput
	ToGetVpnListPolicyObjectEntryArrayOutputWithContext(context.Context) GetVpnListPolicyObjectEntryArrayOutput
}

type GetVpnListPolicyObjectEntryArray []GetVpnListPolicyObjectEntryInput

func (GetVpnListPolicyObjectEntryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnListPolicyObjectEntry)(nil)).Elem()
}

func (i GetVpnListPolicyObjectEntryArray) ToGetVpnListPolicyObjectEntryArrayOutput() GetVpnListPolicyObjectEntryArrayOutput {
	return i.ToGetVpnListPolicyObjectEntryArrayOutputWithContext(context.Background())
}

func (i GetVpnListPolicyObjectEntryArray) ToGetVpnListPolicyObjectEntryArrayOutputWithContext(ctx context.Context) GetVpnListPolicyObjectEntryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnListPolicyObjectEntryArrayOutput)
}

type GetVpnListPolicyObjectEntryOutput struct{ *pulumi.OutputState }

func (GetVpnListPolicyObjectEntryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnListPolicyObjectEntry)(nil)).Elem()
}

func (o GetVpnListPolicyObjectEntryOutput) ToGetVpnListPolicyObjectEntryOutput() GetVpnListPolicyObjectEntryOutput {
	return o
}

func (o GetVpnListPolicyObjectEntryOutput) ToGetVpnListPolicyObjectEntryOutputWithContext(ctx context.Context) GetVpnListPolicyObjectEntryOutput {
	return o
}

// VPN ID or range of VPN IDs e.g., `100` or `200-300`
func (o GetVpnListPolicyObjectEntryOutput) VpnId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnListPolicyObjectEntry) string { return v.VpnId }).(pulumi.StringOutput)
}

type GetVpnListPolicyObjectEntryArrayOutput struct{ *pulumi.OutputState }

func (GetVpnListPolicyObjectEntryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnListPolicyObjectEntry)(nil)).Elem()
}

func (o GetVpnListPolicyObjectEntryArrayOutput) ToGetVpnListPolicyObjectEntryArrayOutput() GetVpnListPolicyObjectEntryArrayOutput {
	return o
}

func (o GetVpnListPolicyObjectEntryArrayOutput) ToGetVpnListPolicyObjectEntryArrayOutputWithContext(ctx context.Context) GetVpnListPolicyObjectEntryArrayOutput {
	return o
}

func (o GetVpnListPolicyObjectEntryArrayOutput) Index(i pulumi.IntInput) GetVpnListPolicyObjectEntryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVpnListPolicyObjectEntry {
		return vs[0].([]GetVpnListPolicyObjectEntry)[vs[1].(int)]
	}).(GetVpnListPolicyObjectEntryOutput)
}

type GetVpnMembershipPolicyDefinitionSite struct {
	// Site list ID
	SiteListId string `pulumi:"siteListId"`
	// Site list version
	SiteListVersion int `pulumi:"siteListVersion"`
	// VPN list IDs
	VpnListIds []string `pulumi:"vpnListIds"`
	// VPN list versions
	VpnListVersions []string `pulumi:"vpnListVersions"`
}

// GetVpnMembershipPolicyDefinitionSiteInput is an input type that accepts GetVpnMembershipPolicyDefinitionSiteArgs and GetVpnMembershipPolicyDefinitionSiteOutput values.
// You can construct a concrete instance of `GetVpnMembershipPolicyDefinitionSiteInput` via:
//
//	GetVpnMembershipPolicyDefinitionSiteArgs{...}
type GetVpnMembershipPolicyDefinitionSiteInput interface {
	pulumi.Input

	ToGetVpnMembershipPolicyDefinitionSiteOutput() GetVpnMembershipPolicyDefinitionSiteOutput
	ToGetVpnMembershipPolicyDefinitionSiteOutputWithContext(context.Context) GetVpnMembershipPolicyDefinitionSiteOutput
}

type GetVpnMembershipPolicyDefinitionSiteArgs struct {
	// Site list ID
	SiteListId pulumi.StringInput `pulumi:"siteListId"`
	// Site list version
	SiteListVersion pulumi.IntInput `pulumi:"siteListVersion"`
	// VPN list IDs
	VpnListIds pulumi.StringArrayInput `pulumi:"vpnListIds"`
	// VPN list versions
	VpnListVersions pulumi.StringArrayInput `pulumi:"vpnListVersions"`
}

func (GetVpnMembershipPolicyDefinitionSiteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnMembershipPolicyDefinitionSite)(nil)).Elem()
}

func (i GetVpnMembershipPolicyDefinitionSiteArgs) ToGetVpnMembershipPolicyDefinitionSiteOutput() GetVpnMembershipPolicyDefinitionSiteOutput {
	return i.ToGetVpnMembershipPolicyDefinitionSiteOutputWithContext(context.Background())
}

func (i GetVpnMembershipPolicyDefinitionSiteArgs) ToGetVpnMembershipPolicyDefinitionSiteOutputWithContext(ctx context.Context) GetVpnMembershipPolicyDefinitionSiteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnMembershipPolicyDefinitionSiteOutput)
}

// GetVpnMembershipPolicyDefinitionSiteArrayInput is an input type that accepts GetVpnMembershipPolicyDefinitionSiteArray and GetVpnMembershipPolicyDefinitionSiteArrayOutput values.
// You can construct a concrete instance of `GetVpnMembershipPolicyDefinitionSiteArrayInput` via:
//
//	GetVpnMembershipPolicyDefinitionSiteArray{ GetVpnMembershipPolicyDefinitionSiteArgs{...} }
type GetVpnMembershipPolicyDefinitionSiteArrayInput interface {
	pulumi.Input

	ToGetVpnMembershipPolicyDefinitionSiteArrayOutput() GetVpnMembershipPolicyDefinitionSiteArrayOutput
	ToGetVpnMembershipPolicyDefinitionSiteArrayOutputWithContext(context.Context) GetVpnMembershipPolicyDefinitionSiteArrayOutput
}

type GetVpnMembershipPolicyDefinitionSiteArray []GetVpnMembershipPolicyDefinitionSiteInput

func (GetVpnMembershipPolicyDefinitionSiteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnMembershipPolicyDefinitionSite)(nil)).Elem()
}

func (i GetVpnMembershipPolicyDefinitionSiteArray) ToGetVpnMembershipPolicyDefinitionSiteArrayOutput() GetVpnMembershipPolicyDefinitionSiteArrayOutput {
	return i.ToGetVpnMembershipPolicyDefinitionSiteArrayOutputWithContext(context.Background())
}

func (i GetVpnMembershipPolicyDefinitionSiteArray) ToGetVpnMembershipPolicyDefinitionSiteArrayOutputWithContext(ctx context.Context) GetVpnMembershipPolicyDefinitionSiteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetVpnMembershipPolicyDefinitionSiteArrayOutput)
}

type GetVpnMembershipPolicyDefinitionSiteOutput struct{ *pulumi.OutputState }

func (GetVpnMembershipPolicyDefinitionSiteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVpnMembershipPolicyDefinitionSite)(nil)).Elem()
}

func (o GetVpnMembershipPolicyDefinitionSiteOutput) ToGetVpnMembershipPolicyDefinitionSiteOutput() GetVpnMembershipPolicyDefinitionSiteOutput {
	return o
}

func (o GetVpnMembershipPolicyDefinitionSiteOutput) ToGetVpnMembershipPolicyDefinitionSiteOutputWithContext(ctx context.Context) GetVpnMembershipPolicyDefinitionSiteOutput {
	return o
}

// Site list ID
func (o GetVpnMembershipPolicyDefinitionSiteOutput) SiteListId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVpnMembershipPolicyDefinitionSite) string { return v.SiteListId }).(pulumi.StringOutput)
}

// Site list version
func (o GetVpnMembershipPolicyDefinitionSiteOutput) SiteListVersion() pulumi.IntOutput {
	return o.ApplyT(func(v GetVpnMembershipPolicyDefinitionSite) int { return v.SiteListVersion }).(pulumi.IntOutput)
}

// VPN list IDs
func (o GetVpnMembershipPolicyDefinitionSiteOutput) VpnListIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVpnMembershipPolicyDefinitionSite) []string { return v.VpnListIds }).(pulumi.StringArrayOutput)
}

// VPN list versions
func (o GetVpnMembershipPolicyDefinitionSiteOutput) VpnListVersions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVpnMembershipPolicyDefinitionSite) []string { return v.VpnListVersions }).(pulumi.StringArrayOutput)
}

type GetVpnMembershipPolicyDefinitionSiteArrayOutput struct{ *pulumi.OutputState }

func (GetVpnMembershipPolicyDefinitionSiteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetVpnMembershipPolicyDefinitionSite)(nil)).Elem()
}

func (o GetVpnMembershipPolicyDefinitionSiteArrayOutput) ToGetVpnMembershipPolicyDefinitionSiteArrayOutput() GetVpnMembershipPolicyDefinitionSiteArrayOutput {
	return o
}

func (o GetVpnMembershipPolicyDefinitionSiteArrayOutput) ToGetVpnMembershipPolicyDefinitionSiteArrayOutputWithContext(ctx context.Context) GetVpnMembershipPolicyDefinitionSiteArrayOutput {
	return o
}

func (o GetVpnMembershipPolicyDefinitionSiteArrayOutput) Index(i pulumi.IntInput) GetVpnMembershipPolicyDefinitionSiteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetVpnMembershipPolicyDefinitionSite {
		return vs[0].([]GetVpnMembershipPolicyDefinitionSite)[vs[1].(int)]
	}).(GetVpnMembershipPolicyDefinitionSiteOutput)
}

type GetZoneBasedFirewallPolicyDefinitionApplyZonePair struct {
	// Destination Zone
	DestinationZone string `pulumi:"destinationZone"`
	// Source Zone
	SourceZone string `pulumi:"sourceZone"`
}

// GetZoneBasedFirewallPolicyDefinitionApplyZonePairInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs and GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionApplyZonePairInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs{...}
type GetZoneBasedFirewallPolicyDefinitionApplyZonePairInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput() GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput
	ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput
}

type GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs struct {
	// Destination Zone
	DestinationZone pulumi.StringInput `pulumi:"destinationZone"`
	// Source Zone
	SourceZone pulumi.StringInput `pulumi:"sourceZone"`
}

func (GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionApplyZonePair)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput() GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput)
}

// GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray and GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray{ GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs{...} }
type GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput() GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput
	ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput
}

type GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray []GetZoneBasedFirewallPolicyDefinitionApplyZonePairInput

func (GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionApplyZonePair)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput() GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput)
}

type GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionApplyZonePair)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput() GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput {
	return o
}

// Destination Zone
func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput) DestinationZone() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionApplyZonePair) string { return v.DestinationZone }).(pulumi.StringOutput)
}

// Source Zone
func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput) SourceZone() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionApplyZonePair) string { return v.SourceZone }).(pulumi.StringOutput)
}

type GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionApplyZonePair)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput() GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput) Index(i pulumi.IntInput) GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetZoneBasedFirewallPolicyDefinitionApplyZonePair {
		return vs[0].([]GetZoneBasedFirewallPolicyDefinitionApplyZonePair)[vs[1].(int)]
	}).(GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRule struct {
	// List of actions entries
	ActionEntries []GetZoneBasedFirewallPolicyDefinitionRuleActionEntry `pulumi:"actionEntries"`
	// Base action
	BaseAction string `pulumi:"baseAction"`
	// List of match entries
	MatchEntries []GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry `pulumi:"matchEntries"`
	// Rule name
	RuleName string `pulumi:"ruleName"`
	// Rule
	RuleOrder int `pulumi:"ruleOrder"`
}

// GetZoneBasedFirewallPolicyDefinitionRuleInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionRuleArgs and GetZoneBasedFirewallPolicyDefinitionRuleOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionRuleInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionRuleArgs{...}
type GetZoneBasedFirewallPolicyDefinitionRuleInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionRuleOutput() GetZoneBasedFirewallPolicyDefinitionRuleOutput
	ToGetZoneBasedFirewallPolicyDefinitionRuleOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionRuleOutput
}

type GetZoneBasedFirewallPolicyDefinitionRuleArgs struct {
	// List of actions entries
	ActionEntries GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayInput `pulumi:"actionEntries"`
	// Base action
	BaseAction pulumi.StringInput `pulumi:"baseAction"`
	// List of match entries
	MatchEntries GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayInput `pulumi:"matchEntries"`
	// Rule name
	RuleName pulumi.StringInput `pulumi:"ruleName"`
	// Rule
	RuleOrder pulumi.IntInput `pulumi:"ruleOrder"`
}

func (GetZoneBasedFirewallPolicyDefinitionRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRule)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleArgs) ToGetZoneBasedFirewallPolicyDefinitionRuleOutput() GetZoneBasedFirewallPolicyDefinitionRuleOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionRuleOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleArgs) ToGetZoneBasedFirewallPolicyDefinitionRuleOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionRuleOutput)
}

// GetZoneBasedFirewallPolicyDefinitionRuleArrayInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionRuleArray and GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionRuleArrayInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionRuleArray{ GetZoneBasedFirewallPolicyDefinitionRuleArgs{...} }
type GetZoneBasedFirewallPolicyDefinitionRuleArrayInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput
	ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput
}

type GetZoneBasedFirewallPolicyDefinitionRuleArray []GetZoneBasedFirewallPolicyDefinitionRuleInput

func (GetZoneBasedFirewallPolicyDefinitionRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionRule)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleArray) ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleArray) ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRule)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleOutput() GetZoneBasedFirewallPolicyDefinitionRuleOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleOutput {
	return o
}

// List of actions entries
func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) ActionEntries() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRule) []GetZoneBasedFirewallPolicyDefinitionRuleActionEntry {
		return v.ActionEntries
	}).(GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput)
}

// Base action
func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) BaseAction() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRule) string { return v.BaseAction }).(pulumi.StringOutput)
}

// List of match entries
func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) MatchEntries() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRule) []GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry {
		return v.MatchEntries
	}).(GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput)
}

// Rule name
func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) RuleName() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRule) string { return v.RuleName }).(pulumi.StringOutput)
}

// Rule
func (o GetZoneBasedFirewallPolicyDefinitionRuleOutput) RuleOrder() pulumi.IntOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRule) int { return v.RuleOrder }).(pulumi.IntOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionRule)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput) Index(i pulumi.IntInput) GetZoneBasedFirewallPolicyDefinitionRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetZoneBasedFirewallPolicyDefinitionRule {
		return vs[0].([]GetZoneBasedFirewallPolicyDefinitionRule)[vs[1].(int)]
	}).(GetZoneBasedFirewallPolicyDefinitionRuleOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleActionEntry struct {
	// Type of action entry
	Type string `pulumi:"type"`
}

// GetZoneBasedFirewallPolicyDefinitionRuleActionEntryInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs and GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionRuleActionEntryInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs{...}
type GetZoneBasedFirewallPolicyDefinitionRuleActionEntryInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput
	ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput
}

type GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs struct {
	// Type of action entry
	Type pulumi.StringInput `pulumi:"type"`
}

func (GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleActionEntry)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput)
}

// GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray and GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray{ GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs{...} }
type GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput
	ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput
}

type GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray []GetZoneBasedFirewallPolicyDefinitionRuleActionEntryInput

func (GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionRuleActionEntry)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleActionEntry)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput {
	return o
}

// Type of action entry
func (o GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRuleActionEntry) string { return v.Type }).(pulumi.StringOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionRuleActionEntry)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput) Index(i pulumi.IntInput) GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetZoneBasedFirewallPolicyDefinitionRuleActionEntry {
		return vs[0].([]GetZoneBasedFirewallPolicyDefinitionRuleActionEntry)[vs[1].(int)]
	}).(GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry struct {
	// policy id for selected match entry
	PolicyId string `pulumi:"policyId"`
	// Should be included with additionally entries for `destinationPort` and `protocol` whenever the type `protocolName` is used.
	ProtocolType string `pulumi:"protocolType"`
	// Type of match entry
	Type string `pulumi:"type"`
	// value for selected match entry
	Value string `pulumi:"value"`
	// variable value for selected match entry if it has variable option (sourceIp & destinationIp)
	ValueVariable string `pulumi:"valueVariable"`
}

// GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs and GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs{...}
type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput
	ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput
}

type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs struct {
	// policy id for selected match entry
	PolicyId pulumi.StringInput `pulumi:"policyId"`
	// Should be included with additionally entries for `destinationPort` and `protocol` whenever the type `protocolName` is used.
	ProtocolType pulumi.StringInput `pulumi:"protocolType"`
	// Type of match entry
	Type pulumi.StringInput `pulumi:"type"`
	// value for selected match entry
	Value pulumi.StringInput `pulumi:"value"`
	// variable value for selected match entry if it has variable option (sourceIp & destinationIp)
	ValueVariable pulumi.StringInput `pulumi:"valueVariable"`
}

func (GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput)
}

// GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayInput is an input type that accepts GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray and GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput values.
// You can construct a concrete instance of `GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayInput` via:
//
//	GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray{ GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs{...} }
type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayInput interface {
	pulumi.Input

	ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput
	ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutputWithContext(context.Context) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput
}

type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray []GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryInput

func (GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry)(nil)).Elem()
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput {
	return i.ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutputWithContext(context.Background())
}

func (i GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput {
	return o
}

// policy id for selected match entry
func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) PolicyId() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry) string { return v.PolicyId }).(pulumi.StringOutput)
}

// Should be included with additionally entries for `destinationPort` and `protocol` whenever the type `protocolName` is used.
func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) ProtocolType() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry) string { return v.ProtocolType }).(pulumi.StringOutput)
}

// Type of match entry
func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry) string { return v.Type }).(pulumi.StringOutput)
}

// value for selected match entry
func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry) string { return v.Value }).(pulumi.StringOutput)
}

// variable value for selected match entry if it has variable option (sourceIp & destinationIp)
func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput) ValueVariable() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry) string { return v.ValueVariable }).(pulumi.StringOutput)
}

type GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput struct{ *pulumi.OutputState }

func (GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry)(nil)).Elem()
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput() GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput) ToGetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutputWithContext(ctx context.Context) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput {
	return o
}

func (o GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput) Index(i pulumi.IntInput) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry {
		return vs[0].([]GetZoneBasedFirewallPolicyDefinitionRuleMatchEntry)[vs[1].(int)]
	}).(GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput)
}

type GetZoneListPolicyObjectEntry struct {
	// Interface name
	Interface string `pulumi:"interface"`
	// VPN ID
	Vpn string `pulumi:"vpn"`
}

// GetZoneListPolicyObjectEntryInput is an input type that accepts GetZoneListPolicyObjectEntryArgs and GetZoneListPolicyObjectEntryOutput values.
// You can construct a concrete instance of `GetZoneListPolicyObjectEntryInput` via:
//
//	GetZoneListPolicyObjectEntryArgs{...}
type GetZoneListPolicyObjectEntryInput interface {
	pulumi.Input

	ToGetZoneListPolicyObjectEntryOutput() GetZoneListPolicyObjectEntryOutput
	ToGetZoneListPolicyObjectEntryOutputWithContext(context.Context) GetZoneListPolicyObjectEntryOutput
}

type GetZoneListPolicyObjectEntryArgs struct {
	// Interface name
	Interface pulumi.StringInput `pulumi:"interface"`
	// VPN ID
	Vpn pulumi.StringInput `pulumi:"vpn"`
}

func (GetZoneListPolicyObjectEntryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneListPolicyObjectEntry)(nil)).Elem()
}

func (i GetZoneListPolicyObjectEntryArgs) ToGetZoneListPolicyObjectEntryOutput() GetZoneListPolicyObjectEntryOutput {
	return i.ToGetZoneListPolicyObjectEntryOutputWithContext(context.Background())
}

func (i GetZoneListPolicyObjectEntryArgs) ToGetZoneListPolicyObjectEntryOutputWithContext(ctx context.Context) GetZoneListPolicyObjectEntryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneListPolicyObjectEntryOutput)
}

// GetZoneListPolicyObjectEntryArrayInput is an input type that accepts GetZoneListPolicyObjectEntryArray and GetZoneListPolicyObjectEntryArrayOutput values.
// You can construct a concrete instance of `GetZoneListPolicyObjectEntryArrayInput` via:
//
//	GetZoneListPolicyObjectEntryArray{ GetZoneListPolicyObjectEntryArgs{...} }
type GetZoneListPolicyObjectEntryArrayInput interface {
	pulumi.Input

	ToGetZoneListPolicyObjectEntryArrayOutput() GetZoneListPolicyObjectEntryArrayOutput
	ToGetZoneListPolicyObjectEntryArrayOutputWithContext(context.Context) GetZoneListPolicyObjectEntryArrayOutput
}

type GetZoneListPolicyObjectEntryArray []GetZoneListPolicyObjectEntryInput

func (GetZoneListPolicyObjectEntryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneListPolicyObjectEntry)(nil)).Elem()
}

func (i GetZoneListPolicyObjectEntryArray) ToGetZoneListPolicyObjectEntryArrayOutput() GetZoneListPolicyObjectEntryArrayOutput {
	return i.ToGetZoneListPolicyObjectEntryArrayOutputWithContext(context.Background())
}

func (i GetZoneListPolicyObjectEntryArray) ToGetZoneListPolicyObjectEntryArrayOutputWithContext(ctx context.Context) GetZoneListPolicyObjectEntryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetZoneListPolicyObjectEntryArrayOutput)
}

type GetZoneListPolicyObjectEntryOutput struct{ *pulumi.OutputState }

func (GetZoneListPolicyObjectEntryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZoneListPolicyObjectEntry)(nil)).Elem()
}

func (o GetZoneListPolicyObjectEntryOutput) ToGetZoneListPolicyObjectEntryOutput() GetZoneListPolicyObjectEntryOutput {
	return o
}

func (o GetZoneListPolicyObjectEntryOutput) ToGetZoneListPolicyObjectEntryOutputWithContext(ctx context.Context) GetZoneListPolicyObjectEntryOutput {
	return o
}

// Interface name
func (o GetZoneListPolicyObjectEntryOutput) Interface() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneListPolicyObjectEntry) string { return v.Interface }).(pulumi.StringOutput)
}

// VPN ID
func (o GetZoneListPolicyObjectEntryOutput) Vpn() pulumi.StringOutput {
	return o.ApplyT(func(v GetZoneListPolicyObjectEntry) string { return v.Vpn }).(pulumi.StringOutput)
}

type GetZoneListPolicyObjectEntryArrayOutput struct{ *pulumi.OutputState }

func (GetZoneListPolicyObjectEntryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetZoneListPolicyObjectEntry)(nil)).Elem()
}

func (o GetZoneListPolicyObjectEntryArrayOutput) ToGetZoneListPolicyObjectEntryArrayOutput() GetZoneListPolicyObjectEntryArrayOutput {
	return o
}

func (o GetZoneListPolicyObjectEntryArrayOutput) ToGetZoneListPolicyObjectEntryArrayOutputWithContext(ctx context.Context) GetZoneListPolicyObjectEntryArrayOutput {
	return o
}

func (o GetZoneListPolicyObjectEntryArrayOutput) Index(i pulumi.IntInput) GetZoneListPolicyObjectEntryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetZoneListPolicyObjectEntry {
		return vs[0].([]GetZoneListPolicyObjectEntry)[vs[1].(int)]
	}).(GetZoneListPolicyObjectEntryOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListInput)(nil)).Elem(), GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayInput)(nil)).Elem(), GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationInput)(nil)).Elem(), GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayInput)(nil)).Elem(), GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnListPolicyObjectEntryInput)(nil)).Elem(), GetVpnListPolicyObjectEntryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnListPolicyObjectEntryArrayInput)(nil)).Elem(), GetVpnListPolicyObjectEntryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnMembershipPolicyDefinitionSiteInput)(nil)).Elem(), GetVpnMembershipPolicyDefinitionSiteArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetVpnMembershipPolicyDefinitionSiteArrayInput)(nil)).Elem(), GetVpnMembershipPolicyDefinitionSiteArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionApplyZonePairInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionApplyZonePairArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionApplyZonePairArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionRuleArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleArrayInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleActionEntryInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayInput)(nil)).Elem(), GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneListPolicyObjectEntryInput)(nil)).Elem(), GetZoneListPolicyObjectEntryArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetZoneListPolicyObjectEntryArrayInput)(nil)).Elem(), GetZoneListPolicyObjectEntryArray{})
	pulumi.RegisterOutputType(GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListOutput{})
	pulumi.RegisterOutputType(GetVpnInterfaceT1E1SerialFeatureTemplateIpv6AccessListArrayOutput{})
	pulumi.RegisterOutputType(GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationOutput{})
	pulumi.RegisterOutputType(GetVpnInterfaceT1E1SerialFeatureTemplateTunnelInterfaceEncapsulationArrayOutput{})
	pulumi.RegisterOutputType(GetVpnListPolicyObjectEntryOutput{})
	pulumi.RegisterOutputType(GetVpnListPolicyObjectEntryArrayOutput{})
	pulumi.RegisterOutputType(GetVpnMembershipPolicyDefinitionSiteOutput{})
	pulumi.RegisterOutputType(GetVpnMembershipPolicyDefinitionSiteArrayOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionApplyZonePairOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionApplyZonePairArrayOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionRuleOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionRuleArrayOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionRuleActionEntryOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionRuleActionEntryArrayOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryOutput{})
	pulumi.RegisterOutputType(GetZoneBasedFirewallPolicyDefinitionRuleMatchEntryArrayOutput{})
	pulumi.RegisterOutputType(GetZoneListPolicyObjectEntryOutput{})
	pulumi.RegisterOutputType(GetZoneListPolicyObjectEntryArrayOutput{})
}
