// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class CiscoSecurityFeatureTemplateKeychainGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Specify the Key ID
        ///   - Range: `0`-`2147483647`
        /// </summary>
        [Input("keyId")]
        public Input<int>? KeyId { get; set; }

        /// <summary>
        /// Specify the name of the Keychain
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Indicates if list item is considered optional.
        /// </summary>
        [Input("optional")]
        public Input<bool>? Optional { get; set; }

        public CiscoSecurityFeatureTemplateKeychainGetArgs()
        {
        }
        public static new CiscoSecurityFeatureTemplateKeychainGetArgs Empty => new CiscoSecurityFeatureTemplateKeychainGetArgs();
    }
}
