// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class FeatureDeviceTemplateGeneralTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Feature template ID
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("subTemplates")]
        private InputList<Inputs.FeatureDeviceTemplateGeneralTemplateSubTemplateArgs>? _subTemplates;

        /// <summary>
        /// List of sub templates
        /// </summary>
        public InputList<Inputs.FeatureDeviceTemplateGeneralTemplateSubTemplateArgs> SubTemplates
        {
            get => _subTemplates ?? (_subTemplates = new InputList<Inputs.FeatureDeviceTemplateGeneralTemplateSubTemplateArgs>());
            set => _subTemplates = value;
        }

        /// <summary>
        /// Feature template type
        ///   - Choices: `cisco_system`, `cisco_logging`, `cedge_aaa`, `cisco_bfd`, `cisco_omp`, `cisco_security`, `cisco_banner`, `cisco_snmp`, `cedge_global`, `cli-template`, `cisco_sig_credentials`, `switchport`, `cisco_thousandeyes`, `cisco_vpn`, `virtual-application-utd`
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Feature template version
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public FeatureDeviceTemplateGeneralTemplateArgs()
        {
        }
        public static new FeatureDeviceTemplateGeneralTemplateArgs Empty => new FeatureDeviceTemplateGeneralTemplateArgs();
    }
}
