// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class ServiceLanVpnFeatureRouteLeakFromGlobalVpnGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("redistributions")]
        private InputList<Inputs.ServiceLanVpnFeatureRouteLeakFromGlobalVpnRedistributionGetArgs>? _redistributions;

        /// <summary>
        /// Redistribute Routes to specific Protocol on Service VPN
        /// </summary>
        public InputList<Inputs.ServiceLanVpnFeatureRouteLeakFromGlobalVpnRedistributionGetArgs> Redistributions
        {
            get => _redistributions ?? (_redistributions = new InputList<Inputs.ServiceLanVpnFeatureRouteLeakFromGlobalVpnRedistributionGetArgs>());
            set => _redistributions = value;
        }

        [Input("routePolicyId")]
        public Input<string>? RoutePolicyId { get; set; }

        /// <summary>
        /// Leak Routes of particular protocol from Global to Service VPN
        ///   - Choices: `static`, `connected`, `bgp`, `ospf`
        /// </summary>
        [Input("routeProtocol")]
        public Input<string>? RouteProtocol { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("routeProtocolVariable")]
        public Input<string>? RouteProtocolVariable { get; set; }

        public ServiceLanVpnFeatureRouteLeakFromGlobalVpnGetArgs()
        {
        }
        public static new ServiceLanVpnFeatureRouteLeakFromGlobalVpnGetArgs Empty => new ServiceLanVpnFeatureRouteLeakFromGlobalVpnGetArgs();
    }
}
