// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class ServiceLanVpnInterfaceEthernetFeatureIpv4VrrpTrackingObjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Decrement Value for VRRP priority
        ///   - Range: `1`-`255`
        /// </summary>
        [Input("decrementValue")]
        public Input<int>? DecrementValue { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("decrementValueVariable")]
        public Input<string>? DecrementValueVariable { get; set; }

        /// <summary>
        /// Track Action
        ///   - Choices: `Decrement`, `Shutdown`
        /// </summary>
        [Input("trackerAction")]
        public Input<string>? TrackerAction { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("trackerActionVariable")]
        public Input<string>? TrackerActionVariable { get; set; }

        [Input("trackerId")]
        public Input<string>? TrackerId { get; set; }

        public ServiceLanVpnInterfaceEthernetFeatureIpv4VrrpTrackingObjectArgs()
        {
        }
        public static new ServiceLanVpnInterfaceEthernetFeatureIpv4VrrpTrackingObjectArgs Empty => new ServiceLanVpnInterfaceEthernetFeatureIpv4VrrpTrackingObjectArgs();
    }
}
