// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class ServiceRoutingOspfv3Ipv4FeatureAreaGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Always translate type7 LSAs
        /// </summary>
        [Input("alwaysTranslate")]
        public Input<bool>? AlwaysTranslate { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("alwaysTranslateVariable")]
        public Input<string>? AlwaysTranslateVariable { get; set; }

        /// <summary>
        /// Set OSPF area number
        ///   - Range: `0`-`4294967295`
        /// </summary>
        [Input("areaNumber")]
        public Input<int>? AreaNumber { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("areaNumberVariable")]
        public Input<string>? AreaNumberVariable { get; set; }

        /// <summary>
        /// Set OSPFv3 area type
        ///   - Choices: `Stub`, `Nssa`, `Normal`
        /// </summary>
        [Input("areaType")]
        public Input<string>? AreaType { get; set; }

        [Input("interfaces")]
        private InputList<Inputs.ServiceRoutingOspfv3Ipv4FeatureAreaInterfaceGetArgs>? _interfaces;

        /// <summary>
        /// Set OSPF interface parameters
        /// </summary>
        public InputList<Inputs.ServiceRoutingOspfv3Ipv4FeatureAreaInterfaceGetArgs> Interfaces
        {
            get => _interfaces ?? (_interfaces = new InputList<Inputs.ServiceRoutingOspfv3Ipv4FeatureAreaInterfaceGetArgs>());
            set => _interfaces = value;
        }

        /// <summary>
        /// Do not inject inter-area routes
        /// </summary>
        [Input("noSummary")]
        public Input<bool>? NoSummary { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("noSummaryVariable")]
        public Input<string>? NoSummaryVariable { get; set; }

        [Input("ranges")]
        private InputList<Inputs.ServiceRoutingOspfv3Ipv4FeatureAreaRangeGetArgs>? _ranges;

        /// <summary>
        /// Summarize OSPF routes at an area boundary
        /// </summary>
        public InputList<Inputs.ServiceRoutingOspfv3Ipv4FeatureAreaRangeGetArgs> Ranges
        {
            get => _ranges ?? (_ranges = new InputList<Inputs.ServiceRoutingOspfv3Ipv4FeatureAreaRangeGetArgs>());
            set => _ranges = value;
        }

        public ServiceRoutingOspfv3Ipv4FeatureAreaGetArgs()
        {
        }
        public static new ServiceRoutingOspfv3Ipv4FeatureAreaGetArgs Empty => new ServiceRoutingOspfv3Ipv4FeatureAreaGetArgs();
    }
}
