// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class ServiceRoutingOspfv3Ipv6FeatureRedistributeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Set the protocol
        ///   - Choices: `Connected`, `Static`, `Omp`, `Bgp`, `Eigrp`
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("protocolVariable")]
        public Input<string>? ProtocolVariable { get; set; }

        [Input("routePolicyId")]
        public Input<string>? RoutePolicyId { get; set; }

        /// <summary>
        /// Translate Rib Metric, Attribute conditional on `Protocol` being equal to `Omp`
        ///   - Default value: `False`
        /// </summary>
        [Input("translateRibMetric")]
        public Input<bool>? TranslateRibMetric { get; set; }

        public ServiceRoutingOspfv3Ipv6FeatureRedistributeArgs()
        {
        }
        public static new ServiceRoutingOspfv3Ipv6FeatureRedistributeArgs Empty => new ServiceRoutingOspfv3Ipv6FeatureRedistributeArgs();
    }
}
