// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class ServiceAppqoeFeatureCombinedServiceNodeGroupGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("serviceNodes")]
        private InputList<Inputs.ServiceAppqoeFeatureCombinedServiceNodeGroupServiceNodeGetArgs>? _serviceNodes;

        /// <summary>
        /// Service Node Information
        /// </summary>
        public InputList<Inputs.ServiceAppqoeFeatureCombinedServiceNodeGroupServiceNodeGetArgs> ServiceNodes
        {
            get => _serviceNodes ?? (_serviceNodes = new InputList<Inputs.ServiceAppqoeFeatureCombinedServiceNodeGroupServiceNodeGetArgs>());
            set => _serviceNodes = value;
        }

        public ServiceAppqoeFeatureCombinedServiceNodeGroupGetArgs()
        {
        }
        public static new ServiceAppqoeFeatureCombinedServiceNodeGroupGetArgs Empty => new ServiceAppqoeFeatureCombinedServiceNodeGroupGetArgs();
    }
}
