// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class TransportManagementVpnFeatureIpv6StaticRouteNextHopGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Address
        /// </summary>
        [Input("address")]
        public Input<string>? Address { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("addressVariable")]
        public Input<string>? AddressVariable { get; set; }

        /// <summary>
        /// Administrative distance
        ///   - Range: `1`-`254`
        ///   - Default value: `1`
        /// </summary>
        [Input("administrativeDistance")]
        public Input<int>? AdministrativeDistance { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("administrativeDistanceVariable")]
        public Input<string>? AdministrativeDistanceVariable { get; set; }

        public TransportManagementVpnFeatureIpv6StaticRouteNextHopGetArgs()
        {
        }
        public static new TransportManagementVpnFeatureIpv6StaticRouteNextHopGetArgs Empty => new TransportManagementVpnFeatureIpv6StaticRouteNextHopGetArgs();
    }
}
