// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class VpnInterfaceEthernetPppoeFeatureTemplateAccessListArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of access list
        /// </summary>
        [Input("aclName")]
        public Input<string>? AclName { get; set; }

        /// <summary>
        /// Variable name
        /// </summary>
        [Input("aclNameVariable")]
        public Input<string>? AclNameVariable { get; set; }

        /// <summary>
        /// Direction
        ///   - Choices: `in`, `out`
        /// </summary>
        [Input("direction")]
        public Input<string>? Direction { get; set; }

        /// <summary>
        /// Indicates if list item is considered optional.
        /// </summary>
        [Input("optional")]
        public Input<bool>? Optional { get; set; }

        public VpnInterfaceEthernetPppoeFeatureTemplateAccessListArgs()
        {
        }
        public static new VpnInterfaceEthernetPppoeFeatureTemplateAccessListArgs Empty => new VpnInterfaceEthernetPppoeFeatureTemplateAccessListArgs();
    }
}
