// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Sdwan.Inputs
{

    public sealed class ZoneListPolicyObjectEntryGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Interface name
        /// </summary>
        [Input("interface")]
        public Input<string>? Interface { get; set; }

        /// <summary>
        /// VPN ID
        /// </summary>
        [Input("vpn")]
        public Input<string>? Vpn { get; set; }

        public ZoneListPolicyObjectEntryGetArgs()
        {
        }
        public static new ZoneListPolicyObjectEntryGetArgs Empty => new ZoneListPolicyObjectEntryGetArgs();
    }
}
