// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This data source can read the IPv4 ACL Policy Definition .
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = sdwan.getIpv4AclPolicyDefinition({
 *     id: "f6b2c44c-693c-4763-b010-895aa3d236bd",
 * });
 * ```
 */
export function getIpv4AclPolicyDefinition(args: GetIpv4AclPolicyDefinitionArgs, opts?: pulumi.InvokeOptions): Promise<GetIpv4AclPolicyDefinitionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sdwan:index/getIpv4AclPolicyDefinition:getIpv4AclPolicyDefinition", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpv4AclPolicyDefinition.
 */
export interface GetIpv4AclPolicyDefinitionArgs {
    /**
     * The id of the object
     */
    id: string;
}

/**
 * A collection of values returned by getIpv4AclPolicyDefinition.
 */
export interface GetIpv4AclPolicyDefinitionResult {
    /**
     * Default action, either `accept` or `drop`
     */
    readonly defaultAction: string;
    /**
     * The description of the policy definition
     */
    readonly description: string;
    /**
     * The id of the object
     */
    readonly id: string;
    /**
     * The name of the policy definition
     */
    readonly name: string;
    /**
     * List of ACL sequences
     */
    readonly sequences: outputs.GetIpv4AclPolicyDefinitionSequence[];
    /**
     * Type
     */
    readonly type: string;
    /**
     * The version of the object
     */
    readonly version: number;
}
/**
 * This data source can read the IPv4 ACL Policy Definition .
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = sdwan.getIpv4AclPolicyDefinition({
 *     id: "f6b2c44c-693c-4763-b010-895aa3d236bd",
 * });
 * ```
 */
export function getIpv4AclPolicyDefinitionOutput(args: GetIpv4AclPolicyDefinitionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetIpv4AclPolicyDefinitionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sdwan:index/getIpv4AclPolicyDefinition:getIpv4AclPolicyDefinition", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getIpv4AclPolicyDefinition.
 */
export interface GetIpv4AclPolicyDefinitionOutputArgs {
    /**
     * The id of the object
     */
    id: pulumi.Input<string>;
}
