// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * This data source can read the Service Object Tracker Feature.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = sdwan.getServiceObjectTrackerFeature({
 *     id: "f6b2c44c-693c-4763-b010-895aa3d236bd",
 *     featureProfileId: "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac",
 * });
 * ```
 */
export function getServiceObjectTrackerFeature(args: GetServiceObjectTrackerFeatureArgs, opts?: pulumi.InvokeOptions): Promise<GetServiceObjectTrackerFeatureResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("sdwan:index/getServiceObjectTrackerFeature:getServiceObjectTrackerFeature", {
        "featureProfileId": args.featureProfileId,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getServiceObjectTrackerFeature.
 */
export interface GetServiceObjectTrackerFeatureArgs {
    /**
     * Feature Profile ID
     */
    featureProfileId: string;
    /**
     * The id of the Feature
     */
    id: string;
}

/**
 * A collection of values returned by getServiceObjectTrackerFeature.
 */
export interface GetServiceObjectTrackerFeatureResult {
    /**
     * The description of the Feature
     */
    readonly description: string;
    /**
     * Feature Profile ID
     */
    readonly featureProfileId: string;
    /**
     * The id of the Feature
     */
    readonly id: string;
    /**
     * interface name
     */
    readonly interface: string;
    /**
     * Variable name
     */
    readonly interfaceVariable: string;
    /**
     * The name of the Feature
     */
    readonly name: string;
    /**
     * Object tracker ID
     */
    readonly objectTrackerId: number;
    /**
     * Variable name
     */
    readonly objectTrackerIdVariable: string;
    /**
     * objectTrackerType:Interface SIG Route
     */
    readonly objectTrackerType: string;
    /**
     * IP address
     */
    readonly routeIp: string;
    /**
     * Variable name
     */
    readonly routeIpVariable: string;
    /**
     * IP mask
     */
    readonly routeMask: string;
    /**
     * Variable name
     */
    readonly routeMaskVariable: string;
    /**
     * The version of the Feature
     */
    readonly version: number;
    /**
     * VPN
     */
    readonly vpn: number;
    /**
     * Variable name
     */
    readonly vpnVariable: string;
}
/**
 * This data source can read the Service Object Tracker Feature.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = sdwan.getServiceObjectTrackerFeature({
 *     id: "f6b2c44c-693c-4763-b010-895aa3d236bd",
 *     featureProfileId: "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac",
 * });
 * ```
 */
export function getServiceObjectTrackerFeatureOutput(args: GetServiceObjectTrackerFeatureOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetServiceObjectTrackerFeatureResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("sdwan:index/getServiceObjectTrackerFeature:getServiceObjectTrackerFeature", {
        "featureProfileId": args.featureProfileId,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getServiceObjectTrackerFeature.
 */
export interface GetServiceObjectTrackerFeatureOutputArgs {
    /**
     * Feature Profile ID
     */
    featureProfileId: pulumi.Input<string>;
    /**
     * The id of the Feature
     */
    id: pulumi.Input<string>;
}
