// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This resource can manage a Localized Policy .
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = new sdwan.LocalizedPolicy("example", {
 *     name: "Example",
 *     description: "My description",
 *     flowVisibilityIpv4: true,
 *     flowVisibilityIpv6: true,
 *     applicationVisibilityIpv4: true,
 *     applicationVisibilityIpv6: true,
 *     cloudQos: true,
 *     cloudQosServiceSide: true,
 *     implicitAclLogging: true,
 *     logFrequency: 1000,
 *     ipv4VisibilityCacheEntries: 1000,
 *     ipv6VisibilityCacheEntries: 1000,
 *     definitions: [{
 *         id: "2081c2f4-3f9f-4fee-8078-dcc8904e368d",
 *         type: "acl",
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * ```sh
 * $ pulumi import sdwan:index/localizedPolicy:LocalizedPolicy example "f6b2c44c-693c-4763-b010-895aa3d236bd"
 * ```
 */
export class LocalizedPolicy extends pulumi.CustomResource {
    /**
     * Get an existing LocalizedPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LocalizedPolicyState, opts?: pulumi.CustomResourceOptions): LocalizedPolicy {
        return new LocalizedPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sdwan:index/localizedPolicy:LocalizedPolicy';

    /**
     * Returns true if the given object is an instance of LocalizedPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LocalizedPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LocalizedPolicy.__pulumiType;
    }

    /**
     * IPv4 application visibility
     *   - Default value: `false`
     */
    declare public readonly applicationVisibilityIpv4: pulumi.Output<boolean>;
    /**
     * IPv6 application visibility
     *   - Default value: `false`
     */
    declare public readonly applicationVisibilityIpv6: pulumi.Output<boolean>;
    /**
     * Cloud QoS
     */
    declare public readonly cloudQos: pulumi.Output<boolean | undefined>;
    /**
     * Cloud QoS service side
     */
    declare public readonly cloudQosServiceSide: pulumi.Output<boolean | undefined>;
    /**
     * List of policy definitions
     */
    declare public readonly definitions: pulumi.Output<outputs.LocalizedPolicyDefinition[] | undefined>;
    /**
     * The description of the localized policy
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * IPv4 flow visibility
     *   - Default value: `false`
     */
    declare public readonly flowVisibilityIpv4: pulumi.Output<boolean>;
    /**
     * IPv6 flow visibility
     *   - Default value: `false`
     */
    declare public readonly flowVisibilityIpv6: pulumi.Output<boolean>;
    /**
     * Implicit ACL logging
     *   - Default value: `false`
     */
    declare public readonly implicitAclLogging: pulumi.Output<boolean>;
    /**
     * IPv4 visibility cache entries
     *   - Range: `16`-`2000000`
     */
    declare public readonly ipv4VisibilityCacheEntries: pulumi.Output<number | undefined>;
    /**
     * IPv6 visibility cache entries
     *   - Range: `16`-`2000000`
     */
    declare public readonly ipv6VisibilityCacheEntries: pulumi.Output<number | undefined>;
    /**
     * Log frequency
     *   - Range: `1`-`2147483647`
     */
    declare public readonly logFrequency: pulumi.Output<number | undefined>;
    /**
     * The name of the localized policy
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The version of the object
     */
    declare public /*out*/ readonly version: pulumi.Output<number>;

    /**
     * Create a LocalizedPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LocalizedPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: LocalizedPolicyArgs | LocalizedPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LocalizedPolicyState | undefined;
            resourceInputs["applicationVisibilityIpv4"] = state?.applicationVisibilityIpv4;
            resourceInputs["applicationVisibilityIpv6"] = state?.applicationVisibilityIpv6;
            resourceInputs["cloudQos"] = state?.cloudQos;
            resourceInputs["cloudQosServiceSide"] = state?.cloudQosServiceSide;
            resourceInputs["definitions"] = state?.definitions;
            resourceInputs["description"] = state?.description;
            resourceInputs["flowVisibilityIpv4"] = state?.flowVisibilityIpv4;
            resourceInputs["flowVisibilityIpv6"] = state?.flowVisibilityIpv6;
            resourceInputs["implicitAclLogging"] = state?.implicitAclLogging;
            resourceInputs["ipv4VisibilityCacheEntries"] = state?.ipv4VisibilityCacheEntries;
            resourceInputs["ipv6VisibilityCacheEntries"] = state?.ipv6VisibilityCacheEntries;
            resourceInputs["logFrequency"] = state?.logFrequency;
            resourceInputs["name"] = state?.name;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as LocalizedPolicyArgs | undefined;
            if (args?.description === undefined && !opts.urn) {
                throw new Error("Missing required property 'description'");
            }
            resourceInputs["applicationVisibilityIpv4"] = args?.applicationVisibilityIpv4;
            resourceInputs["applicationVisibilityIpv6"] = args?.applicationVisibilityIpv6;
            resourceInputs["cloudQos"] = args?.cloudQos;
            resourceInputs["cloudQosServiceSide"] = args?.cloudQosServiceSide;
            resourceInputs["definitions"] = args?.definitions;
            resourceInputs["description"] = args?.description;
            resourceInputs["flowVisibilityIpv4"] = args?.flowVisibilityIpv4;
            resourceInputs["flowVisibilityIpv6"] = args?.flowVisibilityIpv6;
            resourceInputs["implicitAclLogging"] = args?.implicitAclLogging;
            resourceInputs["ipv4VisibilityCacheEntries"] = args?.ipv4VisibilityCacheEntries;
            resourceInputs["ipv6VisibilityCacheEntries"] = args?.ipv6VisibilityCacheEntries;
            resourceInputs["logFrequency"] = args?.logFrequency;
            resourceInputs["name"] = args?.name;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LocalizedPolicy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LocalizedPolicy resources.
 */
export interface LocalizedPolicyState {
    /**
     * IPv4 application visibility
     *   - Default value: `false`
     */
    applicationVisibilityIpv4?: pulumi.Input<boolean>;
    /**
     * IPv6 application visibility
     *   - Default value: `false`
     */
    applicationVisibilityIpv6?: pulumi.Input<boolean>;
    /**
     * Cloud QoS
     */
    cloudQos?: pulumi.Input<boolean>;
    /**
     * Cloud QoS service side
     */
    cloudQosServiceSide?: pulumi.Input<boolean>;
    /**
     * List of policy definitions
     */
    definitions?: pulumi.Input<pulumi.Input<inputs.LocalizedPolicyDefinition>[]>;
    /**
     * The description of the localized policy
     */
    description?: pulumi.Input<string>;
    /**
     * IPv4 flow visibility
     *   - Default value: `false`
     */
    flowVisibilityIpv4?: pulumi.Input<boolean>;
    /**
     * IPv6 flow visibility
     *   - Default value: `false`
     */
    flowVisibilityIpv6?: pulumi.Input<boolean>;
    /**
     * Implicit ACL logging
     *   - Default value: `false`
     */
    implicitAclLogging?: pulumi.Input<boolean>;
    /**
     * IPv4 visibility cache entries
     *   - Range: `16`-`2000000`
     */
    ipv4VisibilityCacheEntries?: pulumi.Input<number>;
    /**
     * IPv6 visibility cache entries
     *   - Range: `16`-`2000000`
     */
    ipv6VisibilityCacheEntries?: pulumi.Input<number>;
    /**
     * Log frequency
     *   - Range: `1`-`2147483647`
     */
    logFrequency?: pulumi.Input<number>;
    /**
     * The name of the localized policy
     */
    name?: pulumi.Input<string>;
    /**
     * The version of the object
     */
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a LocalizedPolicy resource.
 */
export interface LocalizedPolicyArgs {
    /**
     * IPv4 application visibility
     *   - Default value: `false`
     */
    applicationVisibilityIpv4?: pulumi.Input<boolean>;
    /**
     * IPv6 application visibility
     *   - Default value: `false`
     */
    applicationVisibilityIpv6?: pulumi.Input<boolean>;
    /**
     * Cloud QoS
     */
    cloudQos?: pulumi.Input<boolean>;
    /**
     * Cloud QoS service side
     */
    cloudQosServiceSide?: pulumi.Input<boolean>;
    /**
     * List of policy definitions
     */
    definitions?: pulumi.Input<pulumi.Input<inputs.LocalizedPolicyDefinition>[]>;
    /**
     * The description of the localized policy
     */
    description: pulumi.Input<string>;
    /**
     * IPv4 flow visibility
     *   - Default value: `false`
     */
    flowVisibilityIpv4?: pulumi.Input<boolean>;
    /**
     * IPv6 flow visibility
     *   - Default value: `false`
     */
    flowVisibilityIpv6?: pulumi.Input<boolean>;
    /**
     * Implicit ACL logging
     *   - Default value: `false`
     */
    implicitAclLogging?: pulumi.Input<boolean>;
    /**
     * IPv4 visibility cache entries
     *   - Range: `16`-`2000000`
     */
    ipv4VisibilityCacheEntries?: pulumi.Input<number>;
    /**
     * IPv6 visibility cache entries
     *   - Range: `16`-`2000000`
     */
    ipv6VisibilityCacheEntries?: pulumi.Input<number>;
    /**
     * Log frequency
     *   - Range: `1`-`2147483647`
     */
    logFrequency?: pulumi.Input<number>;
    /**
     * The name of the localized policy
     */
    name?: pulumi.Input<string>;
}
