// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * This resource can manage a Policy Object Expanded Community List Policy_object.
 *   - Minimum SD-WAN Manager version: `20.12.0`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = new sdwan.PolicyObjectExpandedCommunityList("example", {
 *     name: "Example",
 *     description: "My Example",
 *     featureProfileId: "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac",
 *     expandedCommunityLists: ["abcd"],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Expected import identifier with the format: "policy_object_expanded_community_list_id,feature_profile_id"
 *
 * ```sh
 * $ pulumi import sdwan:index/policyObjectExpandedCommunityList:PolicyObjectExpandedCommunityList example "f6b2c44c-693c-4763-b010-895aa3d236bd,f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac"
 * ```
 */
export class PolicyObjectExpandedCommunityList extends pulumi.CustomResource {
    /**
     * Get an existing PolicyObjectExpandedCommunityList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyObjectExpandedCommunityListState, opts?: pulumi.CustomResourceOptions): PolicyObjectExpandedCommunityList {
        return new PolicyObjectExpandedCommunityList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sdwan:index/policyObjectExpandedCommunityList:PolicyObjectExpandedCommunityList';

    /**
     * Returns true if the given object is an instance of PolicyObjectExpandedCommunityList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyObjectExpandedCommunityList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyObjectExpandedCommunityList.__pulumiType;
    }

    /**
     * The description of the Policy_object
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Expanded Community List
     */
    declare public readonly expandedCommunityLists: pulumi.Output<string[]>;
    /**
     * Variable name
     */
    declare public readonly expandedCommunityListsVariable: pulumi.Output<string | undefined>;
    /**
     * Feature Profile ID
     */
    declare public readonly featureProfileId: pulumi.Output<string>;
    /**
     * The name of the Policy_object
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The version of the Policy_object
     */
    declare public /*out*/ readonly version: pulumi.Output<number>;

    /**
     * Create a PolicyObjectExpandedCommunityList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyObjectExpandedCommunityListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyObjectExpandedCommunityListArgs | PolicyObjectExpandedCommunityListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyObjectExpandedCommunityListState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["expandedCommunityLists"] = state?.expandedCommunityLists;
            resourceInputs["expandedCommunityListsVariable"] = state?.expandedCommunityListsVariable;
            resourceInputs["featureProfileId"] = state?.featureProfileId;
            resourceInputs["name"] = state?.name;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as PolicyObjectExpandedCommunityListArgs | undefined;
            if (args?.expandedCommunityLists === undefined && !opts.urn) {
                throw new Error("Missing required property 'expandedCommunityLists'");
            }
            if (args?.featureProfileId === undefined && !opts.urn) {
                throw new Error("Missing required property 'featureProfileId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["expandedCommunityLists"] = args?.expandedCommunityLists;
            resourceInputs["expandedCommunityListsVariable"] = args?.expandedCommunityListsVariable;
            resourceInputs["featureProfileId"] = args?.featureProfileId;
            resourceInputs["name"] = args?.name;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyObjectExpandedCommunityList.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PolicyObjectExpandedCommunityList resources.
 */
export interface PolicyObjectExpandedCommunityListState {
    /**
     * The description of the Policy_object
     */
    description?: pulumi.Input<string>;
    /**
     * Expanded Community List
     */
    expandedCommunityLists?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Variable name
     */
    expandedCommunityListsVariable?: pulumi.Input<string>;
    /**
     * Feature Profile ID
     */
    featureProfileId?: pulumi.Input<string>;
    /**
     * The name of the Policy_object
     */
    name?: pulumi.Input<string>;
    /**
     * The version of the Policy_object
     */
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a PolicyObjectExpandedCommunityList resource.
 */
export interface PolicyObjectExpandedCommunityListArgs {
    /**
     * The description of the Policy_object
     */
    description?: pulumi.Input<string>;
    /**
     * Expanded Community List
     */
    expandedCommunityLists: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Variable name
     */
    expandedCommunityListsVariable?: pulumi.Input<string>;
    /**
     * Feature Profile ID
     */
    featureProfileId: pulumi.Input<string>;
    /**
     * The name of the Policy_object
     */
    name?: pulumi.Input<string>;
}
