// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * This resource can manage a Service Tracker Group Feature.
 *   - Minimum SD-WAN Manager version: `20.12.0`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as sdwan from "@pulumi/sdwan";
 *
 * const example = new sdwan.ServiceTrackerGroupFeature("example", {
 *     name: "Example",
 *     description: "My Example",
 *     featureProfileId: "f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac",
 *     trackerElements: [{
 *         trackerId: "615d948f-34ee-4a2e-810e-a9bd8d3d48ec",
 *     }],
 *     trackerBoolean: "or",
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Expected import identifier with the format: "service_tracker_group_feature_id,feature_profile_id"
 *
 * ```sh
 * $ pulumi import sdwan:index/serviceTrackerGroupFeature:ServiceTrackerGroupFeature example "f6b2c44c-693c-4763-b010-895aa3d236bd,f6dd22c8-0b4f-496c-9a0b-6813d1f8b8ac"
 * ```
 */
export class ServiceTrackerGroupFeature extends pulumi.CustomResource {
    /**
     * Get an existing ServiceTrackerGroupFeature resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ServiceTrackerGroupFeatureState, opts?: pulumi.CustomResourceOptions): ServiceTrackerGroupFeature {
        return new ServiceTrackerGroupFeature(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'sdwan:index/serviceTrackerGroupFeature:ServiceTrackerGroupFeature';

    /**
     * Returns true if the given object is an instance of ServiceTrackerGroupFeature.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ServiceTrackerGroupFeature {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ServiceTrackerGroupFeature.__pulumiType;
    }

    /**
     * The description of the Feature
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Feature Profile ID
     */
    declare public readonly featureProfileId: pulumi.Output<string>;
    /**
     * The name of the Feature
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * tracker ref list combine boolean and or
     *   - Choices: `and`, `or`
     *   - Default value: `or`
     */
    declare public readonly trackerBoolean: pulumi.Output<string | undefined>;
    /**
     * Variable name
     */
    declare public readonly trackerBooleanVariable: pulumi.Output<string | undefined>;
    /**
     * tracker parcel ref list
     */
    declare public readonly trackerElements: pulumi.Output<outputs.ServiceTrackerGroupFeatureTrackerElement[] | undefined>;
    /**
     * The version of the Feature
     */
    declare public /*out*/ readonly version: pulumi.Output<number>;

    /**
     * Create a ServiceTrackerGroupFeature resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServiceTrackerGroupFeatureArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ServiceTrackerGroupFeatureArgs | ServiceTrackerGroupFeatureState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ServiceTrackerGroupFeatureState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["featureProfileId"] = state?.featureProfileId;
            resourceInputs["name"] = state?.name;
            resourceInputs["trackerBoolean"] = state?.trackerBoolean;
            resourceInputs["trackerBooleanVariable"] = state?.trackerBooleanVariable;
            resourceInputs["trackerElements"] = state?.trackerElements;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as ServiceTrackerGroupFeatureArgs | undefined;
            if (args?.featureProfileId === undefined && !opts.urn) {
                throw new Error("Missing required property 'featureProfileId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["featureProfileId"] = args?.featureProfileId;
            resourceInputs["name"] = args?.name;
            resourceInputs["trackerBoolean"] = args?.trackerBoolean;
            resourceInputs["trackerBooleanVariable"] = args?.trackerBooleanVariable;
            resourceInputs["trackerElements"] = args?.trackerElements;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ServiceTrackerGroupFeature.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ServiceTrackerGroupFeature resources.
 */
export interface ServiceTrackerGroupFeatureState {
    /**
     * The description of the Feature
     */
    description?: pulumi.Input<string>;
    /**
     * Feature Profile ID
     */
    featureProfileId?: pulumi.Input<string>;
    /**
     * The name of the Feature
     */
    name?: pulumi.Input<string>;
    /**
     * tracker ref list combine boolean and or
     *   - Choices: `and`, `or`
     *   - Default value: `or`
     */
    trackerBoolean?: pulumi.Input<string>;
    /**
     * Variable name
     */
    trackerBooleanVariable?: pulumi.Input<string>;
    /**
     * tracker parcel ref list
     */
    trackerElements?: pulumi.Input<pulumi.Input<inputs.ServiceTrackerGroupFeatureTrackerElement>[]>;
    /**
     * The version of the Feature
     */
    version?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a ServiceTrackerGroupFeature resource.
 */
export interface ServiceTrackerGroupFeatureArgs {
    /**
     * The description of the Feature
     */
    description?: pulumi.Input<string>;
    /**
     * Feature Profile ID
     */
    featureProfileId: pulumi.Input<string>;
    /**
     * The name of the Feature
     */
    name?: pulumi.Input<string>;
    /**
     * tracker ref list combine boolean and or
     *   - Choices: `and`, `or`
     *   - Default value: `or`
     */
    trackerBoolean?: pulumi.Input<string>;
    /**
     * Variable name
     */
    trackerBooleanVariable?: pulumi.Input<string>;
    /**
     * tracker parcel ref list
     */
    trackerElements?: pulumi.Input<pulumi.Input<inputs.ServiceTrackerGroupFeatureTrackerElement>[]>;
}
